### PR TITLE
Fix stuck in loading in my account tab (fixes #1841)

### LINKED ISSUE #1841: JetBrains: Current tier is stuck at "Loading..." in My Account tab on restarting IDE
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.10-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Close the IDE and reopen it
4. Open Cody window and check `My Account` tab

### Observed behavior:
Tier status for "Current tier" will never load and stuck at "Loading..."

### Expected behavior:
Current tier should show the correct value.

### Additional context

**Video link:**

https://drive.google.com/file/d/1qS_MANbTYrS4oycascPfwseFZCskgyb2/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes #1841.

## Test plan
1. log in to a pro account
2. close the project
3. reopen the project

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt [hunk 1]
```diff
@@ -3,18 +3,24 @@ package com.sourcegraph.cody.auth
...
 import com.sourcegraph.cody.initialization.Activity
 
 class SelectOneOfTheAccountsAsActive : Activity {
 
   override fun runActivity(project: Project) {
-    if (CodyAuthenticationManager.getInstance(project).hasNoActiveAccount()) {
-      val newActiveAccount =
-          CodyAuthenticationManager.getInstance(project).getAccounts().getFirstAccountOrNull()
-      CodyAuthenticationManager.getInstance(project).setActiveAccount(newActiveAccount)
+    // It is possible that CodyProjectActiveAccountHolder loads the account from the state omitting
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt:13]: > It is possible that

Can you elaborate on that?
Shouldn't we then change it in `PersistentActiveAccountHolder::loadState`?

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt:13]:
```
@State(
    name = "CodyActiveAccount",
    storages = [Storage(StoragePathMacros.WORKSPACE_FILE)],
    reportStatistic = false)
@Service(Service.Level.PROJECT)
class CodyProjectActiveAccountHolder : PersistentActiveAccountHolder<CodyAccount>() {

  override fun accountManager() = service<CodyAccountManager>()

  override fun notifyActiveAccountMissing() {}

  companion object {
    @JvmStatic
    fun getInstance(project: Project): CodyProjectActiveAccountHolder {
      return project.service<CodyProjectActiveAccountHolder>()
    }
  }
}
```

File: src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt [hunk 2]
```diff
@@ -3,18 +3,24 @@ package com.sourcegraph.cody.auth
...
+    // setActiveAccount() call. We need the call to happen as it propagates the configuration
+    // changes to the agent and the account settings changes to the UI.
+    val initialAccount =
+        CodyProjectActiveAccountHolder.getInstance(project).account
+            ?: CodyAuthenticationManager.getInstance(project).getAccounts().getFirstAccountOrNull()
+    if (initialAccount == null) {
       // The call to refreshPanelsVisibility() is needed to update the UI when there is no account.
       CodyToolWindowContent.executeOnInstanceIfNotDisposed(project) { refreshPanelsVisibility() }
+    } else {
+      CodyAuthenticationManager.getInstance(project).setActiveAccount(initialAccount)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt:23]: Does it make ay sense to `setActiveAccount` also if active account was already set?

File: src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt (hunk 1 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt:13]: The class persists the account when we close the IDE. And sets the account back on restart skipping CodyAuthenticationManager.setActiveAccount.

File: src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt (hunk 2 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt:23]: Here, it can be loaded from memory but not yet actually set (not propagated to the agent, not reflected in our UI). Technically, we do often `setActiveAccount` if the active account is set when we switch the accounts.

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt (hunk 1 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt:13]: Summary

- The present solution works. 
- We cannot call setActiveAccount from loadState b/c it results with infinite recursive call (stackoverflow).
- IMO we have a guarantee that loadState happens before setActiveAccount as loadStates happens in CodyProjectActiveAccountHolder constructor (indirectly)

so the present solution is good enough, but

We should revisit this design. It seems that CodyProjectActiveAccountHolder and CodyAuthenticationManager could be merged into a single class.

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/auth/SelectOneOfTheAccountsAsActive.kt:13]: https://linear.app/sourcegraph/issue/CODY-2666/merge-codyprojectactiveaccountholder-and-codyauthenticationmanager
