### PR TITLE
Properly handle VSCode Positions

### LINKED ISSUE #1623: bug: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
### Cody Version

main

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

error when running document code

### Expected behavior

n/a

### Additional context

[idea.log](https://github.com/sourcegraph/jetbrains/files/15424453/idea.log)

Document command crashes when cursor is on a single line:

https://github.com/sourcegraph/jetbrains/assets/51868853/97a26942-1510-4326-be0a-79d39242d776

Edit command command crashes when cursor is on a single line:

https://github.com/sourcegraph/jetbrains/assets/51868853/ba7dfe8d-eb5c-4cd6-84ee-6e7faebf56e1

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/1623

## Test plan

1. Open sourcegraph/cody
2. Open agent/src/index.test.ts
3. Put cursor in some nested code. I used line with accessToken: 'REDACTED_0ba08837494d00e3943c46999589eb29a210ba8063f084fff511c8e4d1503909',
4. Try to run any edit command

It should fail before my fix and pass after.

Also, I added unittests :)

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/edit/fixupActions/ReplaceUndoableAction.kt [hunk 1]
```diff
@@ -68,9 +68,11 @@ class ReplaceUndoableAction : FixupUndoableAction {
 
   private fun createBeforeMarker(): RangeMarker? {
     val range = edit.range ?: return null
-    if (range.start.line == -1 || range.end.line == -1) return null
-    val startOffset = document.getLineStartOffset(range.start.line) + range.start.character
-    val endOffset = document.getLineStartOffset(range.end.line) + range.end.character
+    if (range.start.isStartOrEndOfDocumentMarker(document) ||
+        range.start.isStartOrEndOfDocumentMarker(document))
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/edit/fixupActions/ReplaceUndoableAction.kt]: a bug here? 🐛

File: src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt [hunk 2]
```diff
@@ -76,14 +75,19 @@ object CodyEditorUtil {
...
+    //    val start =
+    //      min(
+    //        document.getLineEndOffset(range.start.line.toInt()),
+    //        document.getLineStartOffset(range.start.line.toInt()) + range.start.character.toInt()
+    //      )
+    //    val end =
+    //      min(
+    //        document.getLineEndOffset(range.end.line.toInt()),
+    //        document.getLineStartOffset(range.end.line.toInt()) + range.end.character.toInt()
+    //      )
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt]: can we remove it?

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/ContextFilesPanel.kt [hunk 3]
```diff
@@ -106,7 +106,8 @@ class ContextFilesPanel(
       val findFileByNioFile = LocalFileSystem.getInstance().findFileByNioFile(contextFilePath)
       if (findFileByNioFile != null) {
         ApplicationManager.getApplication().invokeLater {
-          OpenFileDescriptor(project, findFileByNioFile, logicalLine, /* logicalColumn= */ 0)
+          OpenFileDescriptor(
+                  project, findFileByNioFile, logicalLine.toInt(), /* logicalColumn= */ 0)
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/chat/ui/ContextFilesPanel.kt:110]: is it possible that we exceed int here? 🤔

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt [hunk 4]
```diff
@@ -1,20 +1,43 @@
 package com.sourcegraph.cody.agent.protocol
 
 import com.intellij.openapi.editor.Document
+import com.intellij.openapi.editor.LogicalPosition
+import kotlin.math.max
+import kotlin.math.min
 
-data class Position(val line: Int, val character: Int) {
+data class Position(@JvmField val line: Long, @JvmField val character: Long) {
+  constructor(line: Int, character: Int) : this(line.toLong(), character.toLong())
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt:9]: hmmm, why don't we use a constructor that takes Longs instead? 🤔

**Comment by RXminuS** [comment]
I would 💯 take credit for aadd all the tests that you've added by also adding them to the test plan 😄

File: src/test/kotlin/com/sourcegraph/cody/agent/protocol/extensions.kt [hunk 5]
```diff
@@ -12,14 +12,9 @@ fun Editor.testing_selectSubstring(substring: String) {
...
-  return startLine + pos.character
-}
-
 fun Editor.testing_substring(range: Range): String {
   return this.document.text.substring(
-      this.testing_offset(range.start), this.testing_offset(range.end))
+      range.start.toOffset(this.document), range.end.toOffset(this.document))
 }
 
 fun Editor.testing_range(substring: String): Range {
```
Comment (RXminuS) [inline src/test/kotlin/com/sourcegraph/cody/agent/protocol/extensions.kt]: testing_range Doesn't seem to be used (anymore?)

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt (hunk 4 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt:9]: Because we often create it from IJ which uses ints, and I do not want to add `toLong` in 50 places ;)

File: src/test/kotlin/com/sourcegraph/cody/agent/protocol/extensions.kt (hunk 5 above)
Comment (pkukielka) [reply src/test/kotlin/com/sourcegraph/cody/agent/protocol/extensions.kt]: Right!

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt (hunk 4 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt:9]: I was afraid that a proper long value could be accidentally converted to int - if that's not a case we are good

**Review by RXminuS — CHANGES_REQUESTED** [review]
~I'm going to be adding some nasty tests that seem to break it...~ @pkukielka Added a basic first one but you'll get the idea :-)

I used to have a whole test suite of these with nasty real world strings that caused all sorts of mayhem. This might be something trivial though because mostly Java and Node should be aligned in their character definitions.

File: src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt (hunk 2 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt]: Done!

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt (hunk 4 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/Position.kt:9]: Kotlin won't accept such conversion without being explicit :)

File: src/main/kotlin/com/sourcegraph/cody/edit/fixupActions/ReplaceUndoableAction.kt (hunk 1 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/edit/fixupActions/ReplaceUndoableAction.kt]: Fixed, thanks!

**Review by RXminuS — APPROVED** [review]
