### PR TITLE
Do not display deprecated llms

### LINKED ISSUE #1827: JetBrains: "No API Key" error occurred when running command with Claude 2.0, 2.1 or Instant
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (6.0.8-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Open any source code file and choose `Claude 2.0 by Anthropic` as LLM
4. Run a command `Execute Code`

### Observed behavior:
Error occurred with "No API key" message

### Expected behavior:
Cody should respond correctly

### Additional context

**Video link:**

https://drive.google.com/file/d/1hDameluAYJCOxsSBZe-Rkdc7yfMVNOtk/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/1827.

- [x] do not show deprecated llms
- [x] migrate old chats
- [x] show migration notification

## Test plan
1. Open IDE with old chats in the history
2. Check if notification is displayed
3. Check if selected model is the new default one
4. Close IDE
5. Open it again and make sure notification window is not displayed again

Cody models upgrade
Cody models upgrade

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt [hunk 1]
```diff
@@ -56,26 +50,20 @@ class LlmDropdown(
...
 
-    models.sortedBy { it.codyProOnly }.forEach(::addItem)
-
-    CodyAuthenticationManager.getInstance(project).getActiveAccountTier().thenApply { accountTier ->
-      if (accountTier == null) return@thenApply
-      isCurrentUserFree = accountTier == AccountTier.DOTCOM_FREE
+    models.filterNot { it.deprecated }.sortedBy { it.codyProOnly }.forEach(::addItem)
 
-      val selectedModel = HistoryService.getInstance(project).getDefaultLlm()
-      val defaultModel =
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt:66]: I think it was a mistake in the code.

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 2]
```diff
@@ -118,6 +129,54 @@ class SettingsMigration : Activity {
...
+              }
+            }
+      }
+
+      if (migratedLlms.isNotEmpty()) {
+        ApplicationManager.getApplication().invokeLater {
+          val msg =
+              """
+              <html>
+              All chats have been upgraded to newer, more capable models. Some old models are no longer supported:<br>
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: can you please bundle this message? also, maybe it would be cleaner if you extract this notification to the separate class?

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 3]
```diff
@@ -118,6 +129,54 @@ class SettingsMigration : Activity {
         }
   }
 
+  fun migrateDeprecatedChatLlms(project: Project) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: btw, is it possible to write a test for it easily?

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt (hunk 2 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: I can extract it to a bundle, but I'm not sure if it makes sense to extract to a separate class if its used only in this one place.

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: Hm, or maybe you mean we could extract whole migration to a separate class?
I can do that.

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt (hunk 3 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: I added a test

**Review by pkukielka — APPROVED** [review]
LGMT
