### PR TITLE
Fix chat history download

### LINKED ISSUE #2274: JetBrains: "Export" button is non functional and user can't export chats.
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  DevKit (242.20224.159)
  PythonCore (242.20224.300)
  idea.plugin.protoeditor (242.20224.155)
  gherkin (242.20224.159)
  com.jetbrains.space (242.20224.155)
  cucumber-java (242.20224.159)
  com.sourcegraph.jetbrains (7.0.3-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Go to Chat History tab and click on `Export` button

### Observed behavior:
`Export` button is not clickable and user can't export chats.

### Expected behavior:
User should be able to export chats

### Additional context

**Screenshot:**

Screenshot 2024-09-12 at 2 52 47 AM

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/2274

## Test plan

1. Open Cody chat history
2. Click "Export History"
3. Select a file and path of your choice to save it
4. Verify that file content contains proper json

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt [hunk 1]
```diff
@@ -151,6 +162,26 @@ internal class WebUIProxy(private val host: WebUIHost, private val browser: JBCe
...
+              callback?.Continue(/* downloadPath = */ "", /* showDialog = */ true)
+            }
+
+            override fun onDownloadUpdated(
+                browser: CefBrowser?,
+                downloadItem: CefDownloadItem?,
+                callback: CefDownloadItemCallback?
+            ) {}
+          },
+          browser.cefBrowser)
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt:183]: is that all? 😮

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt:183]: Yep ^^ Also no Cody changes needed.

Comment (abeatrix) [reply src/main/kotlin/com/sourcegraph/cody/ui/web/WebUIProxy.kt:183]: You are a wizards 🧙!

**Review by abeatrix — APPROVED** [review]
