### PR TITLE
Polish the enterprise enhanced context selector

### LINKED ISSUE #1322: Enterprise repo picker follow up polish
These are follow up issues from #982 and code review feedback on #1308

```[tasklist]
### Tasks
- [ ] Add [tooltip](https://jetbrains.design/intellij/controls/tooltip/) on hover of "Chat Context" for enterprise users with below text.
- [ ] Remove the "Help" toolbar icon, make the toolbar icon one entry tall (at least in Enterprise), and make the minimum size smaller.
- [x] Dismiss the repo selection window when clicking outside of it
- [ ] The cmd-enter to accept language is small and low contrast, but we are using the theme colors; consider using autosave on close @danielmarquespt
- [ ] Add "Cody Context" entry as part of the [Search Everywhere](https://www.jetbrains.com/help/idea/searching-everywhere.html)
- [ ] Add "Cody Context" as part of the Keymap list on JetBrains settings
- [ ] Try to switch to Action
- [ ] Make tree view reflect language below
- [ ] Show the "inferred" repo, exact UX TBD @danielmarquespt
- [ ] Consider switching to ActionManager.createActionToolbar to get more toolbar padding like the git log viewer. Note sporadic problem with the toolbar button hot zone being the right hand side of the button.
- [ ] When individual repos are un/checked, reflect that in the count in the summary line ("Chat Context X repos ...")
- [ ] #1318
- [ ] Make it accept full URLs and strip the https://
```

Tooltip text:

```
About chat context
Select up to 10 repositories from [customer_instance_url] to use as reference context in this chat.
 
[Context Docs](https://sourcegraph.com/docs/cody/core-concepts/context)
```

Tree view language:

```
Chat Context X repos on [instance]
    Repositories
         example/example
         example/example2
```

### LINKED ISSUE #1425: JetBrains: Remote repo popup window size is not adequate.
### Cody Version

v5.5.8-nightly

### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (5.5.8-nightly)

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Click on pencil icon to open remote repo popup window
4. Start adding repo

### Observed behavior:

After adding third repo, the popup size seems very small

### Expected behavior

Remote repo popup window should be bigger to show all repo URLs.

### Additional context

**Screenshot:**

Screenshot 2024-05-01 at 12 25 07 AM

### LINKED ISSUE #1532: JetBrains: Slowness observed while selecting/deselecting repo from chat context.
### Cody Version

v5.5.11-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.11-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user(SG04 instance)
3. Add remote repo in chat context
4. Try selecting/deselecting repo using checkbox

### Observed behavior:
Slowness observed while selecting/deselecting repo

### Expected behavior

Repo selection should be quick and lag free.

### Additional context

**Video link:**

https://drive.google.com/file/d/1TkR9Fmpo5dauOE8CPbeOddRDgNKI5jwp/view?usp=drive_link

### LINKED ISSUE #1542: JetBrains: Automatically recognized repo got deselected when closing and reopening IDE.
### Cody Version

v5.5.11-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.11-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Open project with enabled Git VCS
4. This repository must be publicly available on GitHub i.e. https://github.com/sourcegraph/cody
5. Verify that the Cody repo is automatically recognized and added to the context
6. Add few more remote repo to the context 
7. Close the IDE and reopen it
8. Check the Chat context window

### Observed behavior:
Automatically recognized repo got deselected.

### Expected behavior

Automatically recognized repo should not be deselected when closing/reopening IDE.

### Additional context

**Video link:**

https://drive.google.com/file/d/1wMfzxatNetkeSd1CP8CdcphE9L5prYxs/view?usp=drive_link

### PR DESCRIPTION
**Pull request by dominiccooney**
Fixes #1322, fixes #1425, fixes #1544, fixes #1532, fixes #1542

To summarize the changes:

- There are some repo resolution caches to make checking and unchecking faster.
- The summary line has been simplified from counting total, ignored, etc. repos to a simple count of repos which will be used (that is, the enabled and not ignored repos, including the automatically included repo if it is not ignored.)
- The automatically included repository is represented in the tree view with a "Project repository" label.
- There's a separator between the tree view and the rest of the chat panel. There's an expansive tooltip when you hover the separator, but not the tree view so the tooltip does not impede expanding and collapsing the tree view.
- The right hand side toolbar is gone, instead, you click on a tree view item to bring up the repo list editor. You can also highlight it with the keyboard and hit "enter".
- If you try to enable more than 10 repositories, you get feedback in the form of an error notification.
- You can select and deselect repositories and they stay in the repository tree view and are saved in chat state.
- The tree view reflects what you wrote in the popup. "Not found" repositories are present with a label. You can delete a repository from the text box to remove it from the tree view.
- The contrast and consistency of icons have been improved.
- The popup is positioned above the repository list, and is larger.
- The intermediate "Repositories" node of the tree view has been removed.

Known bugs/caveats:

- When selecting/deselecting repositories in the tree view with the keyboard, the item loses focus as the view is reconstructed.
- You can add an eleventh repository by specifying 10 repositories that are not the automatically included repository. This one goes up to 11.
- Loading a chat with a de-selecting repository that has since been filtered and checking it will result in the "ignored" state appearing. This is because Cody Ignore is applied at late stage of remote repo handling.
- Some of the new icons proposed in the design are not incorporated. There are many overlapping versions of the design for this component... I have to draw a line under this and handle any other feedback as follow-ups.
- This does not address the https feedback in issue #1322; https URLs are filed in #1354 and will be looked at separately.
- Repositories where the entered spec and the resolved name are different may present as duplicates with one "not found."

## Test plan

Tested locally

Screenshot 2024-05-28 at 19 19 09

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/Pluralize.kt [hunk 1]
```diff
@@ -1,8 +1,9 @@
 package com.sourcegraph.cody.chat.ui
 
-// Can pluralize "file", "line" and "repo" by adding -s
+// Can pluralize "file", "line", "repo" and "repository"
 fun String.pluralize(count: Int): String =
```
Comment (RXminuS) [inline src/main/kotlin/com/sourcegraph/cody/chat/ui/Pluralize.kt:4]: I think I like the `ts` version we have of this better that just allows you to either pass the original or an alternative string based on the count. Just because things like "index", "analysis", "matrix", "regex", "appendix" etc all don't work. I've attempted too many times to make good lemmatizers/pluralizers and it's fricking hard.

```ts
//lib/shared/src/common/index.ts
export function pluralize(string: string, count: number | bigint, plural = `${string}s`): string {
    return count === 1 || count === 1n ? string : plural
}
```

File: src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt [hunk 2]
```diff
@@ -0,0 +1,343 @@
...
+  // What the user actually wrote
+  @Volatile var rawSpec: String = ""
+
+  // `rawSpec` after parsing and de-duping. This defines the order in which to display repositories.
+  var specified: Set<String> = emptySet()
+
+  // The names of repositories that have been manually deselected.
+  var manuallyDeselected: Set<String> = emptySet()
+
+  // What the TypeScript extension told us it is using for context.
```
Comment (RXminuS) [inline src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt]: What do you mean with the typescript extension, ~the agent~?

File: src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt [hunk 3]
```diff
@@ -0,0 +1,343 @@
...
+) {
+  private val logger = Logger.getInstance(EnterpriseEnhancedContextStateController::class.java)
+  private val model_ = EnterpriseEnhancedContextModel()
+  private var epoch = 0
+
+  val rawSpec: String
+    get(): String = model_.rawSpec
+
+  private fun <T> withModel(f: (EnterpriseEnhancedContextModel) -> T): T {
+    assert(!ApplicationManager.getApplication().isDispatchThread) {
```
Comment (RXminuS) [inline src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt:99]: Maybe nicer to do similar to the `@RequiresEdt` function annotations we have

File: src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt [hunk 4]
```diff
@@ -0,0 +1,343 @@
...
+   */
+  fun updateRawSpec(newSpec: String) {
+    val speculative = withModel { model ->
+      model.rawSpec = newSpec
+      val speculative = newSpec.split(Regex("""\s+""")).filter { it != "" }.toSet().toList()
+
+      // If a repository name has been removed from the list of speculative repos, then forget that
+      // it
+      // was manually
+      // deselected in order for it to be default selected if it is added back.
```
Comment (dominiccooney) [inline src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt]:
```suggestion
      // If a repository name has been removed from the list of speculative repos, then forget that
      // it was manually deselected in order for it to be default selected if it is added back.
```

File: src/main/kotlin/com/sourcegraph/cody/context/RemoteRepoInsight.kt [hunk 5]
```diff
@@ -49,24 +44,48 @@ enum class RepoInclusion {
   MANUAL,
 }
 
+enum class RepoEnablement {
+  /** The user manually deselected the repository. */
+  DESELECTED,
```
Comment (RXminuS) [inline src/main/kotlin/com/sourcegraph/cody/context/RemoteRepoInsight.kt:49]: Nit: Opposite of DESELECTED is SELECTED, opposite of ENABLED is DISABLED

File: src/main/kotlin/com/sourcegraph/cody/context/RemoteRepoInsight.kt [hunk 6]
```diff
@@ -49,24 +44,48 @@ enum class RepoInclusion {
...
-    val inclusion: RepoInclusion? = null
+    /**
+     * Null in the case of "not found" repos, or manually deselected repos we did not try to find.
+     */
+    val id: String?,
+    val enablement: RepoEnablement,
+    val isIgnored: Boolean,
+    val inclusion: RepoInclusion,
 ) {
+  val isEnabled: Boolean
```
Comment (RXminuS) [inline src/main/kotlin/com/sourcegraph/cody/context/RemoteRepoInsight.kt:66]: This naming conflict could be confusing. I'd probably call the RepoEnabelment `RepoCondition` and have the variants be `SELECTED`, `DESELECTED`, `NOT_FOUND`

**Comment by danielmarquespt** [comment]
Looks really good! @dominiccooney 

A few details that we can try:
- [ ] 1. Use the hint style of the tree node to display additional info like Project Repository
- [ ] 2. We can also present those details in parentheses (Project Repository) to create a better differentiation
- [ ] 3. Change the "Ignored by Admin" to "Restricted by Admin" to move away from the Ignore naming
- [ ] 4. Make the restricted repos use a disabled checkbox

Screenshot 2024-05-28 at 13 17 34

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/Pluralize.kt (hunk 1 above)
Comment (dominiccooney) [reply src/main/kotlin/com/sourcegraph/cody/chat/ui/Pluralize.kt:4]: - We only need to pluralize a few things and they're mentioned in the comment.
- Having a singular or plural works for many languages including English, but not all (for example, Arabic has different cases for zero, one, two, few, many ...) While we only don't localize right now, having the list of things we pluralize in one place seems better than spreading it out to callsites.

File: src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt (hunk 2 above)
Comment (dominiccooney) [reply src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt]: @steveyegge will appreciate your comment.

To me, saying "the Agent" to mean "anything delivered through the Agent protocol and layer" is a bit like saying "I went on a beachside vacation at Airbus A330." Yes, you did use the A330 to get to the beach, but the beach is not the A330.

It is a useful distinction, because while the Agent is written in TypeScript, it is not used by VSCode and hence not in the shared code I'm trying to refer to by "the TypeScript extension."

But I realize I have lost this battle before it begins, so I'll update the comment.

File: src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt (hunk 3 above)
Comment (dominiccooney) [reply src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt:99]: Those annotations do nothing, so I'm not using them.

When the annotations support Kotlin and actually do something, we can replace these assertions with annotations.

**Comment by dominiccooney** [comment]
> Looks really good! @dominiccooney
> 
> A few details that we can try:
> 
> * [ ]  1. Use the hint style of the tree node to display additional info like Project Repository

I'm not 100% sure what hint style means technically, but I am already styling that differently. The presentation you see is a limitation of 2022.x.

> * [ ]  2. We can also present those details in parentheses (Project Repository) to create a better differentiation
> * [ ]  3. Change the "Ignored by Admin" to "Restricted by Admin" to move away from the Ignore naming

Not sure if the change from sentence to Title Case is intentional here, so I have added the parentheses but not changed the case.

> * [ ]  4. Make the restricted repos use a disabled checkbox

Not doing this, see the thread in Loom.

Here's how it looks in 2024.1:

Screenshot 2024-05-28 at 22 10 32

**Comment by danielmarquespt** [comment]
> Not sure if the change from sentence to Title Case is intentional here, so I have added the parentheses but not changed the case.

It was not intentional, sorry. You did the right thing

> Here's how it looks in 2024.1:

I see. Ignore the feedback about the hint then

File: src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt (hunk 3 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt:99]: That is not strictly true @dominiccooney . They do have effect, but I think only for the newer IntelliJ versions:

https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/util/concurrency/annotations/RequiresEdt.java


```
/**
 * Methods and constructors annotated with {@code RequiresEdt} must be called from the Event Dispatch Thread only.
 * Parameters annotated with {@code RequiresEdt} must be callables and are guaranteed to be called from the Event Dispatch Thread.
 * <p/>
 * Aside from a documentation purpose, the annotation is processed by the {@link org.jetbrains.jps.devkit.threadingModelHelper}.
 * The plugin instruments annotated elements with {@link Application#assertIsDispatchThread()} calls
 * to ensure annotation's contract is not violated at runtime. The instrumentation can be disabled
 * by setting {@link RequiresEdt#generateAssertion()} to {@code false}.
 * <p/>
 * <b>Important:</b> the instrumentation has limitations. Please read the docs
 * of the {@link org.jetbrains.jps.devkit.threadingModelHelper} to learn about them.
 *
 * @see <a href="https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html">General Threading Rules</a>
 * @see Application#assertIsDispatchThread()
 * @see Application#invokeLater(Runnable, ModalityState)
 * @see Application#invokeAndWait(Runnable, ModalityState)
 */
```

Comment (dominiccooney) [reply src/main/kotlin/com/sourcegraph/cody/context/EnterpriseEnhancedContextStateController.kt:99]: @pkukielka I'm aware of that, but I believe the annotation processor doesn't do Kotlin?

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/Pluralize.kt (hunk 1 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/chat/ui/Pluralize.kt:4]: In my opinion, the proper way to handle grammar inflections is keeping the rules encoded in the string that needs to be inflected. For example:
```
pluralize(1, "repositor[y|ies]") == "1 repository" 
pluralize(2, "repositor[y|ies]") == "2 repositories"
pluralize(3, "blind [mouse|mice]") == "3 blind mice"
pluralize(10, "h4xx3d b0x[|en]") == "10 h4xx3d b0xen"
pluralize(-32767, "sheep[|]") == "-32767 sheep" 
```

This rule can be extended to support languages with more than two grammatical numbers.
