### PR TITLE
Fix executing command from context menu when project is reopened

### LINKED ISSUE #356: bug: `CommandsTab` caches `project` on project close & open
I managed to get this error:

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=Sourcegraph, containerState=DISPOSE_COMPLETED, componentStore=/Users/mkondratek/runIdeProjects/jetbrains) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:34)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:686)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:659)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:622)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getInstance(CodyAgentService.kt:106)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getAgent(CodyAgentService.kt:96)
	at com.sourcegraph.cody.agent.CodyAgentService.getAgent(CodyAgentService.kt)
	at com.sourcegraph.telemetry.GraphQlLogger.logEvent(GraphQlLogger.java:68)
	at com.sourcegraph.telemetry.GraphQlLogger.logCodyEvent(GraphQlLogger.java:35)
	at com.sourcegraph.cody.commands.ui.CommandsTabPanel.executeCommandWithContext$lambda$2(CommandsTabPanel.kt:47)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I started my investigation... 🕵️‍♂️
It looks like the component saves the previous `project` after I reopen the project.

## Steps to reproduce
1. open a project 
2. open Cody tool window (chat - it will initialize `CommandsTab` correctly)
3. run `Explain Code` from the context menu
4. it works
5. close Cody tool window
6. close the project
7. open the same project (or any other probably)
8. run `Explain Code` from the context menu
9. the error

## Expected behavior 
- the value of `project` is not cached on project closes & open events
- the context menu actions are enabled as soon as the agent is ready (regardless of Cody tool window being opened)

### PR DESCRIPTION
**Pull request by Sa1to**
It fixes: https://github.com/sourcegraph/jetbrains/issues/356 
## Test plan
* Open project and run command from context menu
* Close project
* Open project again
* Run command from context menu

### CODE REVIEW

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsContextMenu.kt [hunk 1]
```diff
@@ -16,15 +16,17 @@ class CommandsContextMenu {
...
-        if (existingAction != null) {
-          continue
-        }
         val action: DumbAwareAction =
             object : DumbAwareAction(commandId.displayName) {
               override fun actionPerformed(e: AnActionEvent) {
                 executeCommand(commandId)
               }
             }
+        if (existingAction != null) {
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsContextMenu.kt:42]: I would like if/else more there instead of `continue` as neither logic branch is more special, but I guess it's purely personal preference.
LGTM

**Review by mkondratek — DISMISSED** [review]
It does not work. 

Please use the same scenario that is given in the issue.

File: src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsContextMenu.kt (hunk 1 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsContextMenu.kt:42]: +1

**Review by pkukielka — APPROVED** [review]
LGTM
