### PR TITLE
Block further inline edits until previous one completes

### LINKED ISSUE #1415: JetBrains: Multiple crashes occurred when user selects "Generate Unit Test" command when Cody is already generating unit test.
### Cody Version

v5.5.7-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.7-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with PRO user
3. Open any source code file
4. Select any code snippet and and select "Generate Unit Test" command from Cody window
5. Verify that Cody starts generating unit test
6. Hit the "Generate Unit Test" button again

### Observed behavior:
Multiple crashes occurred with following stacktraces,
Stacktrace:
```text
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 36,4,main] 1884626291 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1677350074
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:143)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:65)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3488)
	at com.intellij.openapi.editor.impl.InlayImpl.dispose(InlayImpl.java:90)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:238)
	at com.sourcegraph.cody.edit.sessions.FixupSession.finish(FixupSession.kt:219)
	at com.sourcegraph.cody.edit.FixupService.cancelActiveSession(FixupService.kt:71)
	at com.sourcegraph.cody.edit.FixupService.setActiveSession(FixupService.kt:64)
	at com.sourcegraph.cody.edit.sessions.FixupSession.triggerDocumentCodeAsync$lambda$2(FixupSession.kt:103)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invokeSuspend(CodyAgentService.kt:185)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.coWithAgent(CodyAgentService.kt:241)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1.invokeSuspend(CodyAgentService.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:182)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
========
Stacktrace:
```text
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[pool-5-thread-1,5,main] 1298261669 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1677350074
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:143)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:65)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3488)
	at com.intellij.openapi.editor.impl.InlayImpl.dispose(InlayImpl.java:90)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:238)
	at com.sourcegraph.cody.edit.sessions.FixupSession.finish(FixupSession.kt:219)
	at com.sourcegraph.cody.edit.FixupService.cancelActiveSession(FixupService.kt:71)
	at com.sourcegraph.cody.edit.FixupService.setActiveSession(FixupService.kt:64)
	at com.sourcegraph.cody.edit.sessions.FixupSession$triggerDocumentCodeAsync$1$1.invoke(FixupSession.kt:112)
	at com.sourcegraph.cody.edit.sessions.FixupSession$triggerDocumentCodeAsync$1$1.invoke(FixupSession.kt:105)
	at com.sourcegraph.cody.edit.sessions.FixupSession$sam$java_util_function_BiFunction$0.apply(FixupSession.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### Expected behavior

Crash should not occur and there should be some prevention mechanism for not running "Generate Unit Test" when one process is ongoing.

### Additional context

**Video link:**

https://drive.google.com/file/d/1TNeNyakQkOTbNihH7nk9Gxtrv8sxM8RN/view?usp=drive_link

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/1415

## Changes

1. Remove active waiting from the code (`waitUntilActiveSessionIsFinished`)
2. Introduce `cancellationToken` which allows us to signal (and wait for) session ending
3. Block "Document Code" and "Generate Unit Test" buttons when other edit is in progress.
    "In-progress" means until Accept lens appears.
    If new edit is started before accepting previous on, previous one automatically gets accepted.

image

## Test plan

Manual testing with Jetbrains plugin.

### CODE REVIEW

**Comment by danielmarquespt** [comment]
> I might want to run an edit, and then open another immediately so I can start typing new instruction while previous edit is still executing.

Agree. And from the technical POV having the option allows for better flexibility in the future regarding having more complex multi tasking scenarios

File: src/main/kotlin/com/sourcegraph/cody/edit/FixupService.kt [hunk 1]
```diff
@@ -76,20 +76,17 @@ class FixupService(val project: Project) : Disposable {
...
-    waitUntilActiveSessionIsFinished()
-    activeSession = session
-  }
-
-  fun waitUntilActiveSessionIsFinished() {
-    while (activeSession != null) {
-      Thread.sleep(100)
+  fun startNewSession(newSession: FixupSession, code: () -> Unit) {
+    activeSession?.let { currentSession ->
+      if (currentSession.isShowingAcceptLens()) currentSession.accept() else currentSession.cancel()
```
Comment (dominiccooney) [inline src/main/kotlin/com/sourcegraph/cody/edit/FixupService.kt]: My $0.02, let's avoid the situation we had with chat repo picking where Kotlin and TypeScript have separate, uncoordinated representations of the same thing. TypeScript has some facility for multiple simultaneous edits, scheduling idle diff computation work to apply edits, autoaccept, etc. Anything it lacks we should add for the benefit of VSCode and JetBrains. If we want to do bespoke stuff for JetBrains (why?) then we should go do the work in TypeScript to refactor policy so it is out of the way first, like we did for the lens displays.

**Review by dominiccooney — APPROVED** [review]
Everything except the blocking to start new sessions looks good to me.

We should not stray from what the TypeScript does in VSCode without a clear justification, otherwise we end up with two overlapping implementations which start to interfere. Where we do want to stray from VSCode, we should go clean up the TypeScript side so there's a hook which will invoke a VSCode path, or a JetBrains path.

@steveyegge mentioned being able to relate edits to the FixupTask that caused them would make it possible to reach back to the related FixupSession. Do we still need that if streaming is off? And if it is what we need so we can get to a simpler, concurrent edits all the time model, then let's do it...

The VSCode API editing event is synchronous. We can maintain a shadow stack of an acting fixup and when we're publishing the edit event, consult the shadow stack to see whether a fixup is the cause.

If there's concurrent edits in JetBrains and Agent, the Agent edit may need to fail and be retried. Let's make an abstraction for applying retryable edits in TypeScript and have fixups (and eventually everything touching buffers) use it.

File: src/main/kotlin/com/sourcegraph/cody/edit/FixupService.kt (hunk 1 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/edit/FixupService.kt]: @dominiccooney that change is needed specifically **because** we decided to temporarily diverge from VSCode implementation.
VSCode supports parallel edits, but Jetbrains currently does not. @steveyegge recently cleaned up `FixupService` and removed edits queue to reflect that fact. That is supposed to be temporary situation, and we wan to make it parallel after GA. But for now, if we only support one edit at a time, we need to deal with UI/UX consequences of that.

If we agree on partially blocking user actions based on the active task state (per my question and @danielmarquespt response) I can (and will :)) simplify this code because situation of two simultaneous edits won't be possible.

File: src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt [hunk 2]
```diff
@@ -41,25 +49,18 @@ class CommandsTabPanel(
...
-    addHierarchyListener {
-      if (!project.isDisposed) {
-        if (it.component.isShowing) {
-          IgnoreOracle.getInstance(project).addListener(this)
-        } else {
-          IgnoreOracle.getInstance(project).removeListener(this)
-        }
-      }
-    }
+    IgnoreOracle.getInstance(project).addListener(this)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt:57]: @dominiccooney I simplified this, I do not see any reason to keep adding and removing this listener.
If there is any, please let me know.

File: src/main/kotlin/com/sourcegraph/cody/commands/CommandId.kt [hunk 3]
```diff
@@ -2,8 +2,8 @@ package com.sourcegraph.cody.commands
 
 import java.awt.event.KeyEvent
 
-enum class CommandId(val displayName: String, val mnemonic: Int) {
-  Explain("Explain Code", KeyEvent.VK_E),
-  Smell("Smell Code", KeyEvent.VK_S),
-  Test("Generate Test", KeyEvent.VK_T)
+enum class CommandId(val id: String, val displayName: String, val mnemonic: Int) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/commands/CommandId.kt:5]: The class is `CommandId` and it has `id` field now. That leads to `commandId.id` which looks weird. Can we remove `Id` from the class name?

File: src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt [hunk 4]
```diff
@@ -245,23 +250,19 @@ abstract class FixupSession(
   }
 
   fun retry() {
-    val instruction = instruction
-
-    undo()
-
-    ApplicationManager.getApplication().executeOnPooledThread {
-      FixupService.getInstance(project).waitUntilActiveSessionIsFinished()
+    cancellationToken.onFinished {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt:251]: Does this call to `onFinished` override the call from the `init` block?

**Review by mkondratek — APPROVED** [review]
minor comments. nothing blocking

File: src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt (hunk 4 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt:251]: Nope, they are stacked:

```kt
  public void onFinished(Consumer<Boolean> callback) {
    this.cancelled.thenAccept(
        (isCancelled) -> {
          try {
            callback.accept(isCancelled);
          } catch (Exception ignored) {
            // Do nothing about exceptions in cancellation callbacks
          }
        });
  }
```

File: src/main/kotlin/com/sourcegraph/cody/commands/CommandId.kt (hunk 3 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/commands/CommandId.kt:5]: Let me do this either on a separate PR or at the end of the reviews... it is used in a quite a few places, I do not want to introduced such amount of noise on this PR.

File: src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt (hunk 2 above)
Comment (dominiccooney) [reply src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt:57]: Should be fine... I was just keen to avoid references from something held on to by agent callbacks *and* the opaque JetBrains machinery. Seems like a recipe for leaks.

File: src/main/kotlin/com/sourcegraph/cody/edit/FixupService.kt (hunk 1 above)
Comment (dominiccooney) [reply src/main/kotlin/com/sourcegraph/cody/edit/FixupService.kt]: > if we only support one edit at a time

That's the issue, basically... the TypeScript extension supports multiple simultaneous edits, so we're accruing some tech debt here: the TypeScript side can't add anything that would cause simultaneous edits for JetBrains. The rest of the team is about to embark on an effort to increase edits/user-day, and we are surreptitiously adding this subtle constraint on them.

The other way to approach this would be to make a one-edit-at-a-time-mode in the TypeScript extension so when they run into the constraint the abstractions push back on them instead of JetBrains breaking.

I defer to your judgement on this one. Getting edits out from behind the flag to get some real world use and feedback is certainly valuable.

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/edit/FixupService.kt]: > The other way to approach this would be to make a one-edit-at-a-time-mode in the TypeScript extension so when they run into the constraint the abstractions push back on them instead of JetBrains breaking.

I'm worrying that it could turn out to be much more complicated and have much more edge cases than we think.
I do not feel it's worth spending that time a week+ before passing GA release to QA.
I will be happy to revisit it afterwards.

File: src/main/kotlin/com/sourcegraph/cody/commands/CommandId.kt (hunk 3 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/commands/CommandId.kt:5]: I think this is acceptable. In fact, such naming seems to be [rather common](https://github.com/search?q=%22Id%28val+id%3A%22&type=code) in Kotlin and Scala code.
