### PR TITLE
 Do not remove deprecated llm (`model`) from the persistence model

### LINKED ISSUE #965: JetBrains: LLM dropdown shows "Unknown by Unknown" when selecting earlier chat from 'Chat History'.
### Installation Information

Plugin version: `5.3.2999-nightly`
IDE version: `IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Install JetBrains IntelliJ IDEA editor and open any git project. 
2. Have Cody plugin installed in your editor.
3. Login to Cody using Google account having a Chat History.
4. Upon successful login, go to 'Chat History' and open any previous chat.

**Observed behavior:**
LLM dropdown values shown as "Unknown by Unknown".

### Expected behavior

LLM values should be correctly shown for historical chats.

### Additional context

**Video link:**

https://drive.google.com/file/d/1twXIim-KCeEmH4u3l0iEILguCDCZXtJG/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/965.

## Test plan
1. with 5.3.1544, delete `"RunOnceActivity.CodyHistoryLlmMigration": "true",` entry from `workspace.xml` if present
2. create multiple chats with each llm
3. having THESE changes run the same project 

expected: the models are (migrated and) DISPLAYED correctly

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 1]
```diff
@@ -96,13 +96,12 @@ class SettingsMigration : Activity {
         .filter { it.llm == null }
         .forEach {
           val (model, provider, title) =
-              modelToProviderAndTitle.getOrDefault(it.model, Triple("", "Default", "Default"))
+              modelToProviderAndTitle.getOrDefault(it.model, Triple(it.model, null, null))
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt:99]: LGTM, but maybe let's do the same change in `createFromState`

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt:99]: 👍

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 2]
```diff
@@ -96,18 +96,18 @@ class SettingsMigration : Activity {
...
+          llmState.title = title
+          llmState.provider = provider
           it.llm = llmState
-          it.model = null
         }
   }
 
   private val modelToProviderAndTitle =
       mapOf(
+          "Claude 2 by Anthropic" to Triple("anthropic/claude-2", "Anthropic", "claude 2"),
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt:110]: For enterprise the model request looks like this:
```
[Trace - 03:55:48 PM] Sending request 'chat/models - (22)'
Params: {
  "id": "553a1e2f-d73d-48a6-a962-2c7271cd6db4"
}


[Trace - 03:55:48 PM] Received response 'chat/models - (22)' in 2ms
Result: {
  "models": [
    {
      "default": true,
      "codyProOnly": false,
      "provider": "Anthropic",
      "title": "claude 2",
      "model": "anthropic/claude-2"
    }
  ]
}
Error: null
```

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt:110]: This line fixes the issue with the failing migration and "Unknown by Unknown" display name

**Review by pkukielka — APPROVED** [review]
LGTM
