### PR TITLE
Fix: Context files are not showing up in the chat

### LINKED ISSUE #328: Context files are not showing up in the chat

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/328.

Requires https://github.com/sourcegraph/cody/pull/3068.

## Test plan 
1. Write to chat / Use commands
2. Verify their replies contain context files when applicable 

---

Note that for now there is no persistence for context files.

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt [hunk 1]
```diff
@@ -230,7 +262,21 @@ private constructor(
...
           })
 
-      chatSession.addMessage(ChatMessage(Speaker.HUMAN, commandId.displayName))
+      chatSession.addMessage(
+          ChatMessage(
+              Speaker.HUMAN,
+              source = commandId.source,
+              commandId.displayName,
+              id = chatSession.messages.count()))
+      val responsePlaceholder =
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:266]: Smart 👌

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt [hunk 2]
```diff
@@ -140,15 +147,38 @@ private constructor(
             extensionMessage.isMessageInProgress == false) {
           getCancellationToken().dispose()
         } else {
-          if (lastMessage?.text != null && extensionMessage.chatID != null) {
-            addAssistantResponseToChat(lastMessage.text, lastMessage.displayText)
+
+          if (extensionMessage.chatID != null) {
+            if (prevLastMessage != null) {
+              if (lastMessage?.contextFiles != messages.lastOrNull()?.contextFiles) {
+                val messageId = extensionMessage.messages.count() - 2
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:154]: When we assign messageId for a first time it's `id = messages.count()`
Why here we need to substract `1` or `2` and not `0` or`1`?
`extensionMessage` have more messages than our `messages`?

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt (hunk 2 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:154]: `id` is an index in the incoming `extensionMessage.messages`- I just calculate that index for the last and prevLast element

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:154]: I know what `id` is, it's not what I was asking about ;)
To me it just seems to be off by one because you need to subtract `-2` instead of `-1` and I do not fully understand why.

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/Speaker.kt [hunk 3]
```diff
@@ -1,12 +1,13 @@
...
+import com.google.gson.JsonDeserializer
 import com.google.gson.annotations.SerializedName
 
 enum class Speaker(val speaker: String) {
   @SerializedName("human") HUMAN("human"),
   @SerializedName("assistant") ASSISTANT("assistant")
 }
 
-val SpeakerSerializer = JsonSerializer<Speaker> { src, _, _ -> JsonPrimitive(src.speaker) }
+val speakerDeserializer = JsonDeserializer { src, _, _ ->
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/protocol/Speaker.kt:11]: this is a fix to the deserialization issue

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ContextFile.kt [hunk 4]
```diff
@@ -61,14 +60,3 @@ val uriSerializer = JsonSerializer { uri: URI, type, context ->
   obj.addProperty("fragment", uri.fragment)
   obj
 }
-
-fun contextFilesFromList(list: List<Any>): List<String> {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/protocol/ContextFile.kt:65]: unused

File: src/main/java/com/sourcegraph/cody/attribution/AttributionSearchCommand.kt [hunk 5]
```diff
@@ -51,7 +49,4 @@ class AttributionSearchCommand(private val project: Project) {
 
   private fun attributionEnabled(): Boolean =
       project.getService(CurrentConfigFeatures::class.java).get().attribution
-
-  private fun findChatSessionFor(messageId: UUID): AgentChatSession? =
```
Comment (mkondratek) [inline src/main/java/com/sourcegraph/cody/attribution/AttributionSearchCommand.kt:55]: unsused

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt (hunk 2 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:154]: `prevLastMessage` has index `extensionMessage.messages.count() - 2`

we are numbering items `0` to `count - 1`

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSessionService.kt [hunk 6]
```diff
@@ -35,9 +34,6 @@ class AgentChatSessionService(private val project: Project) {
   fun getSession(sessionId: SessionId): AgentChatSession? =
       chatSessions.find { it.hasSessionId(sessionId) }
 
-  fun findByMessage(messageId: UUID): AgentChatSession? =
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSessionService.kt:38]: unused

File: src/main/kotlin/com/sourcegraph/cody/chat/actions/BaseCommandAction.kt [hunk 7]
```diff
@@ -10,15 +10,15 @@ import com.sourcegraph.cody.commands.CommandId
 
 abstract class BaseCommandAction : BaseChatAction() {
 
-  abstract fun myCommandId(): CommandId
+  abstract val myCommandId: CommandId
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/chat/actions/BaseCommandAction.kt:13]: unrel fix (the one Jakub asked for)

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt (hunk 2 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:154]: Ah, because when we get messages count message is not tagged yet. I see.

File: build.gradle.kts [hunk 8]
```diff
@@ -199,7 +199,7 @@ tasks {
     return destinationDir
   }
 
-  val codyCommit = "70e927ce69c75aea5b2053574333e6525b717ba3"
+  val codyCommit = "ef011c45c0b28446aaf5921e8080b4492469b5fb"
```
Comment (Sa1to) [inline build.gradle.kts:202]: Is it required for this PR? If not i thought that we should update cody commit in separate PRs.

Comment (pkukielka) [reply build.gradle.kts:202]: It's relevant. Also it's just one commit cherry-picked on the previous cody commit.
