### PR TITLE
Fix missing progress indicator on autocompletion loading

### LINKED ISSUE #312: bug: No visual indicator when autocomplete is running
### Installation Information

IntelliJ IDEA 2023.2 (Community Edition)
Build #IC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.sourcegraph.jetbrains (5.2.18630-nightly)

Kotlin: 232-1.9.0-IJ8660.185

### Describe the bug

The Cody icon shows no visual indication that an autocomplete is attempting to be generated

### Expected behavior

Previously the Cody icon would spin when it was attempting to generate an autocomplete.  There should be some indication that it is currently attempting to generate an autocomplete.

### Additional context (logs, images, etc)

_No response_

### PR DESCRIPTION
**Pull request by mkondratek**
image

Note it's a π PR ❗ 

--- 

This PR fixes the missing progress indicator on the autocompletion loading (fixes https://github.com/sourcegraph/jetbrains/issues/312).

## Test plan
- play with autocomplete

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt [hunk 1]
```diff
@@ -228,36 +229,39 @@ class CodyAutocompleteManager {
...
+              }
+              null
             }
-            null
-          }
-          .thenAccept {
-            resetApplication(project)
-            result.complete(null)
-          }
+            .completeOnTimeout(null, 3, TimeUnit.SECONDS)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt:256]: I think it's 4 sec in some other place, maybe we need a global setting to be consistent.

**Review by pkukielka — APPROVED** [review]
LGTM
