### PR TITLE
Fix misleading Commands buttons look on the IntelliJ's New UI

### LINKED ISSUE #1527: Commands panel buttons don't look like buttons
On `v.5.5.11` the buttons in the Commands panel don't look like buttons.

Image

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/1527

## Test plan

Open Cody Commands tab with IntelliJ's [New UI  ](https://www.jetbrains.com/help/idea/new-ui.html) enabled and see if buttons looks right.

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt [hunk 1]
```diff
@@ -100,9 +102,10 @@ class CommandsTabPanel(
     buttons[actionId] = button
 
     button.layout = BorderLayout()
-    button.border = BorderFactory.createEmptyBorder(0, 5, 0, 10)
     ActionManagerEx.getInstanceEx().getAction(actionId).shortcutSet.shortcuts.firstOrNull()?.let {
-      button.add(JLabel(KeymapUtil.getShortcutText(it)), BorderLayout.LINE_END)
+      val shortcutLabel = JLabel(KeymapUtil.getShortcutText(it))
+      shortcutLabel.border = BorderFactory.createEmptyBorder(0, 0, 0, 10)
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt:107]: Pls double check that works correctly for this matrix

| | New UI | Old UI |
| --- | --- | --- |
| Light Theme | 1 | 2 |
| Dark Theme | 3 | 4 |

**Review by mkondratek — APPROVED** [review]

File: src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt (hunk 1 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/commands/ui/CommandsTabPanel.kt:107]: Checked - all works fine now 👍
