### PR TITLE
Move update channel setting to Cody & Sourcegraph

### LINKED ISSUE #57369: JetBrains: make it easier to use the Alpha channel
Alpha channel releases are instantly approved on the JetBrains Marketplace. We should leverage this fact to improve QA:

- Always cut an alpha channel release alongside stable releases so that internal teammates can reliably stay on the alpha channel. This would have allowed us to catch the 3.4.0 regression in the 24hr window between the release cut and the release getting approved.
- Add an easy to use setting to toggle between stable/alpha channel similar to Copilot. This avoids the manual step to remove/add the alpha channel repository URL via Plugins > Cogwheel > "Manage Plugin Repositories" https://plugins.jetbrains.com/plugins/list?channel=alpha&pluginId=9682

----

_This action was created from [Incident 246](https://app.incident.io/sourcegraph/incidents/246) by Olaf Geirsson, using [incident.io](https://app.incident.io) 🔥_

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/sourcegraph/issues/57369

https://github.com/sourcegraph/jetbrains/pull/9 has been prematurely merged.

This PR moves the update channel setting from Cody to Cody & Sourcegraph.

image

### Manual

1. runIde
2. go to Settings / Plugins / gaer icon / Manage plugin repositories
3. verify there are no repositories
4. go to Settings / Tools / Sourcegraph & Cody
5. Switch Update channel to Nightly
6. go to Settings / Plugins / gaer icon / Manage plugin repositories
7. verify there is alpha repository added
8. go to Settings / Tools / Sourcegraph & Cody
9. Switch Update channel back to Stable
10. go to Settings / Plugins / gaer icon / Manage plugin repositories
11. verify there are no repositories

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/config/ui/AccountConfigurable.kt [hunk 1]
```diff
@@ -30,6 +33,7 @@ class AccountConfigurable(val project: Project) :
   private val accountsModel = CodyAccountListModel(project)
   private val activeAccountHolder = project.service<CodyProjectActiveAccountHolder>()
   private lateinit var dialogPanel: DialogPanel
+  var channel: UpdateChannel = findConfiguredChannel()
```
Comment (exigow) [inline src/main/kotlin/com/sourcegraph/cody/config/ui/AccountConfigurable.kt]: this var should be private

**Comment by exigow** [comment]
Looks good to me :+1: (except for that one var visibility - you must have overlooked it while moving the code).

**Review by exigow — APPROVED** [review]

**Comment by mkondratek** [comment]
Fixes https://github.com/sourcegraph/sourcegraph/issues/57369
