### PR TITLE
Disable Inline Edit actions when a user is not signed in (fixes #1517)

### LINKED ISSUE #1517: bug: Invoking inline edit while not logged in causes an error
### Cody Version

baed3871ad6d34b41e2a2c56258ccf4a52ae764e

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022

## Steps to reproduce

1. Open a project. Make sure you're not logged into a Cody account.
2. Right click on some code. Select Cody → Edit Code...
3. Type a prompt and click "Edit Code".
4. The action lens will appear, but no actual changes will be made. An error will be logged into idea.log.

### Expected behavior

The actions should be invisible or inactive

### Additional context

```
java.lang.IllegalStateException: No active account
	at com.sourcegraph.cody.history.HistoryService.getOrCreateActiveAccountEntry(HistoryService.kt:146)
	at com.sourcegraph.cody.history.HistoryService.setDefaultLlm(HistoryService.kt:92)
	at com.sourcegraph.cody.chat.ui.LlmDropdown.setSelectedItem(LlmDropdown.kt:94)
	at com.sourcegraph.cody.chat.ui.LlmDropdown$updateModelsInUI$3.invoke$lambda$3(LlmDropdown.kt:69)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes #1517.

## Test plan
1. Log out 
2. Review Cody actions (context menu, Edit Code... in particular)

Actions should be visible but disabled.

## Before 
image

Disable Actions visible in the status widget action group when a user is not logged in.
Disable Actions are above Settings and Mange Accounts (which is not very inviting).

## Now
image
image

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/edit/actions/InlineEditAction.kt [hunk 1]
```diff
@@ -6,10 +6,22 @@ import com.intellij.openapi.actionSystem.PlatformDataKeys
...
 import com.intellij.openapi.project.Project
+import com.sourcegraph.cody.config.CodyAuthenticationManager
+import com.sourcegraph.common.CodyBundle
 
 abstract class InlineEditAction : AnAction(), DumbAware {
   private val logger = Logger.getInstance(InlineEditAction::class.java)
 
+  override fun update(event: AnActionEvent) {
+    val project = event.project ?: return
+    val hasActiveAccount = !CodyAuthenticationManager.getInstance(project).hasNoActiveAccount()
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/edit/actions/InlineEditAction.kt]: I would consider adding `hasActiveAccount` as well if we need negation in so many places.

**Review by pkukielka — APPROVED** [review]
I added one small remark but overall LGTM

File: src/main/resources/CodyBundle.properties [hunk 2]
```diff
@@ -165,6 +165,7 @@ action.sourcegraph.openFindPopup.text=Find with Sourcegraph...
 action.sourcegraph.openFindPopup.description=Search all your repos on Sourcegraph
 action.sourcegraph.login.text=Log in to Sourcegraph
 action.sourcegraph.login.description=Log in to Sourcegraph
+action.sourcegraph.disabled.description=Log In to Sourcegraph to enable Cody features
```
Comment (odisseus) [inline src/main/resources/CodyBundle.properties]: Use consistent capitalisation. It should be either sentence case or [title case](https://en.wikipedia.org/wiki/Capitalization#Titles).

**Review by odisseus — APPROVED** [review]
