### PR TITLE
Fix free/pro account switching and enterprise invalid token state 

### LINKED ISSUE #1816: JetBrains: Account switching from Free to Pro and vice versa is not working correctly.
### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
org.jetbrains.plugins.hocon (2023.1.0)
PythonCore (233.14475.9)
com.soywiz.korge.korge-intellij-plugin (4.0.4)
com.sourcegraph.jetbrains (6.0.8-nightly)
Kotlin: 233.14475.28-IJ

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Have both Free and Pro account logged in to Cody
3. Switch account from Free to Pro
4. Go to Cody and check "My Account" tab

### Observed behavior:
Account change is not reflected in "My Account" tab and it is keep showing "Free" as a current tier.

### Additional context

**Video link:**

https://drive.google.com/file/d/1--dE3CDcPUJRwzMQEgzYiV1Uq81mYZqo/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/1816.

## Test plan
1. Switch between free and pro accounts
2. The changes should be reflected immediately in the UI

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt [hunk 1]
```diff
@@ -125,7 +128,7 @@ class CodyToolWindowContent(private val project: Project) {
       allContentLayout.show(allContentPanel, ONBOARDING_PANEL)
       return
     }
-    allContentLayout.show(allContentPanel, MAIN_PANEL)
+    //    allContentLayout.show(allContentPanel, MAIN_PANEL)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt]: Commented out code?

File: src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt [hunk 2]
```diff
@@ -83,74 +84,58 @@ class CodyAuthenticationManager(val project: Project) : Disposable {
...
-    val account = getActiveAccount() ?: return CompletableFuture.completedFuture(null)
-    val previousAccountTier = activeAccountTier?.getNow(null)
-    val accountTierFuture = CompletableFuture<AccountTier?>()
-    activeAccountTier = accountTierFuture
+    isTokenInvalid = isTokenInvalidFuture
+    tier = tierFuture
 
-    accountTierFuture.thenApply { currentAccountTier ->
-      if (previousAccountTier != currentAccountTier) {
+    tierFuture.thenApply { currentAccountTier ->
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt:99]: Looks like we are publisher notification both in `getAuthenticationState` and `setActiveAccount`. Won't that cause some of the notification to be sent twice?
Somehow I'm not sure about that whole design we have there.

File: src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt [hunk 3]
```diff
@@ -159,7 +144,23 @@ class CodyAuthenticationManager(val project: Project) : Disposable {
...
     }
 
-    return isTokenInvalidFuture
+    return authenticationState
+  }
+
+  /**
+   * User account type can change because users can renew or cancel their subscriptions at any time.
+   * Components which state depends on this property should be checking state of
+   * `getActiveAccountTier` in non-blocking way or listen for `AccountSettingChangeContext` events
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt:153]: Where is that used?

**Review by pkukielka — APPROVED** [review]
LGTM, but honestly I think we should add tests for it now.
I think maybe they wouldn't even required agent as we query the graphql directly.
