### PR TITLE
Fix misleading error message when user token is unavailable

### LINKED ISSUE #224: bug: Removing all existing tokens leads to hard to understand user facing errors
### Installation Information

How to reproduce:
1. Remove your existing tokens at https://sourcegraph.com/users/{username}/settings/tokens
2. Run IntelliJ from main branch. I was testing with 2023.1: `/gradlew :runIDE -PplatformRuntimeVersion=2023.1`

### Describe the bug

IDE complains about mismatching agent id. That is kind of internal implementation detail, it should either not happen or be presented in a way which is actionable and understandable to user. In this case adding new token fixes the issue, so what is point of that error?

image

```
java.lang.Throwable: User id in JetBrains is different from agent
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.sourcegraph.cody.CodyToolWindowContent.addNewSubscriptionTab(CodyToolWindowContent.kt:145)
	at com.sourcegraph.cody.CodyToolWindowContent.access$addNewSubscriptionTab(CodyToolWindowContent.kt:48)
	at com.sourcegraph.cody.CodyToolWindowContent$refreshSubscriptionTab$1$1.invoke(CodyToolWindowContent.kt:123)
	at com.sourcegraph.cody.CodyToolWindowContent$refreshSubscriptionTab$1$1.invoke(CodyToolWindowContent.kt:121)
	at com.sourcegraph.cody.CodyToolWindowContent$refreshSubscriptionTab$1.invoke$lambda$0(CodyToolWindowContent.kt:121)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
	at com.sourcegraph.cody.CodyToolWindowContent$refreshSubscriptionTab$1.invoke(CodyToolWindowContent.kt:121)
	at com.sourcegraph.cody.CodyToolWindowContent$refreshSubscriptionTab$1.invoke(CodyToolWindowContent.kt:119)
	at com.intellij.vcs.log.BaseSingleTaskControllerKt.runInEdtAsync$lambda$0(BaseSingleTaskController.kt:59)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Expected behavior

No error is thrown, I think?

### Additional context (logs, images, etc)

_No response_

### PR DESCRIPTION
**Pull request by Sa1to**
It fixes #224 
## Test plan
* Add account on one version of IJ
* Open another version of IJ with cody installed
* Deny access to keychain
* Prompt about adding missing token should be displayed

https://github.com/sourcegraph/jetbrains/assets/9321940/ff5f7923-875d-40a1-bcdf-81f38c0f8bd7

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt [hunk 1]
```diff
@@ -142,7 +142,10 @@ class CodyToolWindowContent(private val project: Project) : UpdatableChat {
         agentUserId = getUserId(server)
       }
       if (jetbrainsUserId != agentUserId) {
-        logger.error("User id in JetBrains is different from agent")
+        if (agentUserId != null) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt:145]: do we want to log `agentUserId is null`? idk, just asking

**Review by mkondratek — APPROVED** [review]

File: src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt (hunk 1 above)
Comment (Sa1to) [reply src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt:145]: It happens only when token was deleted on the website so in this case we should just prompt user to add valid account

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt:145]: We should cove that case with a proper popup (like when user deny a keyring access) but that is rather separate issue. Please do not forgot to make a ticket for it @Sa1to :)
