### PR TITLE
Do not run EDT code in  CodyFixHighlightPass:doCollectInformation

### LINKED ISSUE #2287: JetBrains: IDE got stuck and user has to force quit it with different actions - Autocomplete & Generate Unit Tests
### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
org.jetbrains.plugins.hocon (2023.1.0)
PythonCore (233.14475.9)
com.soywiz.korge.korge-intellij-plugin (4.0.4)
com.sourcegraph.jetbrains (7.0.3-nightly)
Kotlin: 233.14475.28-IJ

### Bug Description

Platform: Windows & macOS both

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open any file and run `Generate Unit Tests` command - Windows
4. Open any file and write code and clean up code and verify Autocomplete triggers - macOS

### Observed behavior:
IDE got stuck and user has to force quit it. 
Above step-3 is observed on Windows and step-4 is observed on macOS

### Expected behavior:
IDE should work smoothly.

### Additional context

**Attachments:**

macOS : https://drive.google.com/file/d/15RC4z9OgdgmxFfWar5WZRvmWeWkEJnD0/view?usp=drive_link
Logs : 
[macOS-idea.log](https://github.com/user-attachments/files/16985502/macOS-idea.log)

Windows: https://drive.google.com/file/d/1oeMwYasVtv2s1hKkJ7EOwvKBBe8mZBSE/view?usp=drive_link
Logs: 
[Windows-idea.log](https://github.com/user-attachments/files/16985495/Windows-idea.log)

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/2287

## Changes 

Looks like we cannot do EDT actions in the `CodyFixHighlightPass:doCollectInformation` or we are risking a deadlock.

## Test plan

It's a bit hard to test deterministically but for me adding and removing few special characters on an empty file was triggering IDE crash pretty quickly (10-20 sec).
I used combination of:

`Option + \` (`«`)
`Option + P` (`Ļ`)
`Backspace`

In a random order.
Timing matters, keep changing the tempo of the keystrokes.

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt [hunk 1]
```diff
@@ -48,36 +47,24 @@ class CodyFixHighlightPass(val file: PsiFile, val editor: Editor) :
...
-                  logger.warn("Failed to convert highlight to protocol diagnostic", x)
-                  null
-                }
-              }
-              .toList()
+        // TODO: We need to check how Enum comparison works to check if we can do things like
+        // >= HighlightSeverity.INFO
+        myHighlights.mapNotNull {
+          try {
+            val range = document.codyRange(it.startOffset, it.endOffset)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt]: `codyRange` already contains the same check.

File: src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt [hunk 2]
```diff
@@ -90,32 +77,19 @@ class CodyFixHighlightPass(val file: PsiFile, val editor: Editor) :
         agent.server.diagnostics_publish(
             Diagnostics_PublishParams(diagnostics = protocolDiagnostics))
 
-        for (highlight in myHighlights) {
+        for (diagnostic in protocolDiagnostics) {
           if (progress.isCanceled) {
             break
           }
 
-          val range =
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/inspections/CodyFixHighlightPass.kt:98]: No need to recompute the same thing again

**Review by mkondratek — APPROVED** [review]
tried it a few times.
 before this change I was able to reproduce it
 after this change I am not able to repro it

lgtm
