### PR TITLE
JetBrains: Agent cleanup on project close

### LINKED ISSUE #8: JetBrains: agent isn't shut down on exit
Noticed a large number of `cody-agentXXXXXX` processes running.  

Details:
- version: 3.4.1
- os: mac 13.4.1, 
- editor: IntelliJ CE

Steps to reproduce:

- Reboot 
- Open Activity monitor verify no cody-agent processes
- Start IntelliJ open project verify in activity monitor 1 `cody-agentXYZ` process
- Exit IntelliJ - see `cody-agentXYZ` process remains active
- Start IntelliJ open a project - see there are now 2 `cody-agentXYZ` processes

Expected behavior:
Exiting editor should terminate the cody agent process.

### PR DESCRIPTION
**Pull request by chwarwick**
The agent was not getting shutdown because the project was already disposed when stop was called which bypassed the process.

This shutdowns the agent process when the project scoped service for agent is disposed, and removes the project listener that had been responsible for shutting down the agent but was calling it the project was disposed. 

closes https://github.com/sourcegraph/jetbrains/issues/8
## Test plan
`./gradlew  :runIDE`  
open a project
Open activity manager verify 1 cody-agent
Open a second project in a new window - verify activity manager shows 2 cody-agent
Test chat & autocomplete in each window
Close one project - verify activity manager shows 1 cody-agent
Test chat & autocomplete in remaining window
Exit current Editor complete
verify activity manager shows no cody-agent

### CODE REVIEW

File: src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt [hunk 1]
```diff
@@ -168,6 +165,7 @@ class CodyAgent(private val project: Project) : Disposable {
   }
 
   override fun dispose() {
+    shutdown()
```
Comment (mkondratek) [inline src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt:168]: nice. It's both a fix and code removal 💟

**Review by mkondratek — APPROVED** [review]

**Comment by chwarwick** [comment]
@mkondratek I don't have write access so I can't merge, if you could that would be helpful.

**Comment by mkondratek** [comment]
@chwarwick done, I hope I did it right 😂
