### PR TITLE
Fix codyErrorSubmitter issues with too long url

### LINKED ISSUE #2231: Crash with too long url
### IDE Information

.

### Bug Description

https://github.com/sourcegraph/jetbrains/issues/new?template=bug_report.yml&labels=bug&projects=sourcegraph/381&title=bug%3A+java.lang.IllegalArgumentException%3A+Invalid+range+specified%3A+%281578%2C+1577%29%3B+&about=IntelliJ+IDEA+2024.2.1+%28Ultimate+Edition%29%0ABuild+%23IU-242.21829.142%2C+built+on+August+28%2C+2024%0ALicensed+to+Kamil+Burzynski%0ASubscription+is+active+until+October+6%2C+2024.%0ARuntime+version%3A+21.0.3%2B13-b509.11+aarch64+%28JCEF+122.1.9%29%0AVM%3A+OpenJDK+64-Bit+Server+VM+by+JetBrains+s.r.o.%0AToolkit%3A+sun.lwawt.macosx.LWCToolkit%0AmacOS+14.6.1%0AGC%3A+G1+Young+Generation%2C+G1+Concurrent+GC%2C+G1+Old+Generation%0AMemory%3A+16384M%0ACores%3A+10%0AMetal+Rendering+is+ON%0ARegistry%3A%0A++actionSystem.playback.typecommand.delay%3D50%0A++debugger.new.tool.window.layout%3Dtrue%0A++vcs.log.index.enable%3Dtrue%0A++ide.experimental.ui%3Dtrue%0A++i18n.locale%3D%0A++terminal.new.ui%3Dtrue%0A++typescript.service.node.arguments%3D--max-old-space-size%3D8192%0A++editor.minimap.enabled%3Dtrue%0ANon-Bundled+Plugins%3A%0A++com.mroche.JsonHelper+%281.3.2%29%0A++String+Manipulation+%289.14.1%29%0A++com.wakatime.intellij.plugin+%2815.0.2%29%0A++ru.adelf.idea.dotenv+%282024.2.1%29%0A++PlantUML+integration+%287.10.1-IJ2023.2%29%0A++org.jetbrains.plugins.github+%28242.21829.162%29%0A++com.sourcegraph.jetbrains+%287.0.0%29%0A++commit-prefix-plugin+%281.4.1%29%0A++com.cral.JSONKeyFinder+%282.0.8%29%0A++com.eny.i18n+%282.6.2%29%0AKotlin%3A+242.21829.142-IJ%0A&logs=Stacktrace%3A%0A%60%60%60text%0Ajava.lang.IllegalArgumentException%3A+Invalid+range+specified%3A+%281578%2C+1577%29%3B+%0A%09at+com.intellij.openapi.util.TextRange.assertProperRange%28TextRange.java%3A288%29%0A%09at+com.intellij.openapi.util.TextRange.assertProperRange%28TextRange.java%3A283%29%0A%09at+com.intellij.openapi.util.TextRange.assertProperRange%28TextRange.java%3A279%29%0A%09at+com.intellij.openapi.util.TextRange.%3Cinit%3E%28TextRange.java%3A42%29%0A%09at+com.intellij.openapi.util.TextRange.%3Cinit%3E%28TextRange.java%3A31%29%0A%09at+com.intellij.openapi.util.TextRange.create%28TextRange.java%3A199%29%0A%09at+com.sourcegraph.utils.CodyEditorUtil.getTextRange%28CodyEditorUtil.kt%3A65%29%0A%09at+com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.displayAgentAutocomplete%28CodyAutocompleteManager.kt%3A360%29%0A%09at+com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult%24lambda%2415%24lambda%2414%28CodyAutocompleteManager.kt%3A335%29%0A%09at+com.intellij.openapi.command.WriteCommandAction.lambda%24runWriteCommandAction%244%28WriteCommandAction.java%3A341%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.lambda%24doRunWriteCommandAction%241%28WriteCommandAction.java%3A147%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%24lambda%244%28AnyThreadWriteThreadingSupport.kt%3A318%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%28AnyThreadWriteThreadingSupport.kt%3A328%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%28AnyThreadWriteThreadingSupport.kt%3A318%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction%28ApplicationImpl.java%3A890%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.lambda%24doRunWriteCommandAction%242%28WriteCommandAction.java%3A145%29%0A%09at+com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand%28CoreCommandProcessor.java%3A226%29%0A%09at+com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand%28CoreCommandProcessor.java%3A188%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.doRunWriteCommandAction%28WriteCommandAction.java%3A154%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.run%28WriteCommandAction.java%3A121%29%0A%09at+com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction%28WriteCommandAction.java%3A341%29%0A%09at+com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction%28WriteCommandAction.java%3A329%29%0A%09at+com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult%24lambda%2415%28CodyAutocompleteManager.kt%3A334%29%0A%09at+com.intellij.util.concurrency.ContextRunnable.run%28ContextRunnable.java%3A27%29%0A%09at+com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed%28TransactionGuardImpl.java%3A229%29%0A%09at+com.intellij.openapi.application.TransactionGuardImpl.access%24100%28TransactionGuardImpl.java%3A22%29%0A%09at+com.intellij.openapi.application.TransactionGuardImpl%241.run%28TransactionGuardImpl.java%3A191%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread%24lambda%241%28AnyThreadWriteThreadingSupport.kt%3A184%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction%28AnyThreadWriteThreadingSupport.kt%3A84%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread%28AnyThreadWriteThreadingSupport.kt%3A183%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread%28ApplicationImpl.java%3A836%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl%242.run%28ApplicationImpl.java%3A424%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead%28AnyThreadWriteThreadingSupport.kt%3A122%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead%28ApplicationImpl.java%3A1162%29%0A%09at+com.intellij.openapi.application.impl.FlushQueue.doRun%28FlushQueue.java%3A78%29%0A%09at+com.intellij.openapi.application.impl.FlushQueue.runNextEvent%28FlushQueue.java%3A119%29%0A%09at+com.intellij.openapi.application.impl.FlushQueue.flushNow%28FlushQueue.java%3A41%29%0A%09at+java.desktop%2Fjava.awt.event.InvocationEvent.dispatch%28InvocationEvent.java%3A318%29%0A%09at+java.desktop%2Fjava.awt.EventQueue.dispatchEventImpl%28EventQueue.java%3A781%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%244.run%28EventQueue.java%3A728%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%244.run%28EventQueue.java%3A722%29%0A%09at+java.base%2Fjava.security.AccessController.doPrivileged%28AccessController.java%3A400%29%0A%09at+java.base%2Fjava.security.ProtectionDomain%24JavaSecurityAccessImpl.doIntersectionPrivilege%28ProtectionDomain.java%3A87%29%0A%09at+java.desktop%2Fjava.awt.EventQueue.dispatchEvent%28EventQueue.java%3A750%29%0A%09at+com.intellij.ide.IdeEventQueue.defaultDispatchEvent%28IdeEventQueue.kt%3A696%29%0A%09at+com.intellij.ide.IdeEventQueue._dispatchEvent%24lambda%2416%28IdeEventQueue.kt%3A590%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead%28AnyThreadWriteThreadingSupport.kt%3A117%29%0A%09at+com.intellij.ide.IdeEventQueue._dispatchEvent%28IdeEventQueue.kt%3A590%29%0A%09at+com.intellij.ide.IdeEventQueue.access%24_dispatchEvent%28IdeEventQueue.kt%3A73%29%0A%09at+com.intellij.ide.IdeEventQueue%24dispatchEvent%24processEventRunnable%241%241%241%241.compute%28IdeEventQueue.kt%3A357%29%0A%09at+com.intellij.ide.IdeEventQueue%24dispatchEvent%24processEventRunnable%241%241%241%241.compute%28IdeEventQueue.kt%3A356%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized%28CoreProgressManager.java%3A843%29%0A%09at+com.intellij.ide.IdeEventQueue%24dispatchEvent%24processEventRunnable%241%241%241.invoke%28IdeEventQueue.kt%3A356%29%0A%09at+com.intellij.ide.IdeEventQueue%24dispatchEvent%24processEventRunnable%241%241%241.invoke%28IdeEventQueue.kt%3A351%29%0A%09at+com.intellij.ide.IdeEventQueueKt%24performActivity%24runnableWithWIL%241.invoke%24lambda%240%28IdeEventQueue.kt%3A1035%29%0A%09at+com.intellij.openapi.application.WriteIntentReadAction.lambda%24run%240%28WriteIntentReadAction.java%3A24%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction%28AnyThreadWriteThreadingSupport.kt%3A84%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction%28ApplicationImpl.java%3A910%29%0A%09at+com.intelli...%0A%60%60%60

### Additional context

_No response_

### LINKED ISSUE #2268: Crash with too long url
### IDE Information

IntelliJ

### Bug Description

https://github.com/sourcegraph/jetbrains/issues/new?template=bug_report.yml&labels=bug&projects=sourcegraph/381&title=bug%3A+java.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp...&about=IntelliJ+IDEA+2024.2.1+%28Ultimate+Edition%29%0ABuild+%23IU-242.21829.142%2C+built+on+August+28%2C+2024%0ALicensed+to+Kamil+Burzynski%0ASubscription+is+active+until+October+6%2C+2024.%0ARuntime+version%3A+21.0.3%2B13-b509.11+aarch64+%28JCEF+122.1.9%29%0AVM%3A+OpenJDK+64-Bit+Server+VM+by+JetBrains+s.r.o.%0AToolkit%3A+sun.lwawt.macosx.LWCToolkit%0AmacOS+14.6.1%0AGC%3A+G1+Young+Generation%2C+G1+Concurrent+GC%2C+G1+Old+Generation%0AMemory%3A+16384M%0ACores%3A+10%0AMetal+Rendering+is+ON%0ARegistry%3A%0A++actionSystem.playback.typecommand.delay%3D50%0A++debugger.new.tool.window.layout%3Dtrue%0A++vcs.log.index.enable%3Dtrue%0A++ide.experimental.ui%3Dtrue%0A++i18n.locale%3D%0A++terminal.new.ui%3Dtrue%0A++typescript.service.node.arguments%3D--max-old-space-size%3D8192%0A++editor.minimap.enabled%3Dtrue%0ANon-Bundled+Plugins%3A%0A++com.mroche.JsonHelper+%281.3.2%29%0A++String+Manipulation+%289.14.1%29%0A++com.wakatime.intellij.plugin+%2815.0.2%29%0A++ru.adelf.idea.dotenv+%282024.2.1%29%0A++PlantUML+integration+%287.10.1-IJ2023.2%29%0A++org.jetbrains.plugins.github+%28242.21829.162%29%0A++com.sourcegraph.jetbrains+%287.0.0%29%0A++commit-prefix-plugin+%281.4.1%29%0A++com.cral.JSONKeyFinder+%282.0.8%29%0A++com.eny.i18n+%282.6.2%29%0AKotlin%3A+242.21829.142-IJ%0A&logs=Stacktrace%3A%0A%60%60%60text%0Ajava.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fservices%2Fapis%2Fcrms%2Fdynamics%2FWebhooks.ts%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fservices%2Fapis%2Fcrms%2Fdynamics%2FWebhooks.ts%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128751%3A19%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A129765%3A18%0A++++at+runNextTicks+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A60%3A5%29%0A++++at+process.processImmediate+%28node%3Ainternal%2Ftimers%3A449%3A9%29%0A++++at+process.topLevelDomainCallback+%28node%3Adomain%3A160%3A15%29%0A++++at+process.callbackTrampoline+%28node%3Ainternal%2Fasync_hooks%3A128%3A24%29%0A++++at+async+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128225%3A44%0A%09at+com.intellij.util.ExceptionUtil.rethrow%28ExceptionUtil.java%3A136%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled%28ProgressIndicatorUtils.java%3A399%29%0A%09at+com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation%28CodyFixHighlightPass.kt%3A133%29%0A%09at+com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation%28TextEditorHighlightingPass.java%3A57%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%242%28PassExecutorService.java%3A418%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows%28trace.kt%3A118%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows%28TraceUtil.java%3A36%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%243%28PassExecutorService.java%3A413%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction%28AnyThreadWriteThreadingSupport.kt%3A291%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction%28ApplicationImpl.java%3A965%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%244%28PassExecutorService.java%3A404%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.lambda%24executeProcessUnderProgress%2413%28CoreProgressManager.java%3A660%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun%28CoreProgressManager.java%3A735%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress%28CoreProgressManager.java%3A691%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress%28CoreProgressManager.java%3A659%29%0A%09at+com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress%28ProgressManagerImpl.java%3A79%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.doRun%28PassExecutorService.java%3A403%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%240%28PassExecutorService.java%3A379%29%0A%09at+com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside%28FileTypeManagerImpl.java%3A802%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%241%28PassExecutorService.java%3A379%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader%28AnyThreadWriteThreadingSupport.kt%3A486%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader%28ApplicationImpl.java%3A178%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.run%28PassExecutorService.java%3A377%29%0A%09at+com.intellij.concurrency.JobLauncherImpl%24VoidForkJoinTask%241.exec%28JobLauncherImpl.java%3A190%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinTask.doExec%28ForkJoinTask.java%3A507%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool%24WorkQueue.topLevelExec%28ForkJoinPool.java%3A1491%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.scan%28ForkJoinPool.java%3A2073%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.runWorker%28ForkJoinPool.java%3A2035%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinWorkerThread.run%28ForkJoinWorkerThread.java%3A187%29%0ACaused+by%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fservices%2Fapis%2Fcrms%2Fdynamics%2FWebhooks.ts%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fservices%2Fapis%2Fcrms%2Fdynamics%2FWebhooks.ts%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128751%3A19%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A129765%3A18%0A++++at+runNextTicks+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A60%3A5%29%0A++++at+process.processImmediate+%28node%3Ainternal%2Ftimers%3A449%3A9%29%0A++++at+process.topLevelDomainCallback+%28node%3Adomain%3A160%3A15%29%0A++++at+process.callbackTrampoline+%28node%3Ainternal%2Fasync_hooks%3A128%3A24%29%0A++++at+async+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128225%3A44%0A%09at+java.base%2Fjava.util.concurrent.CompletableFuture.reportGet%28CompletableFuture.java%3A396%29%0A%09at+java.base%2Fjava.util.concurrent.CompletableFuture.get%28CompletableFuture.java%3A2096%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled%28ProgressIndicatorUtils.java%3A370%29%0A%09...+27+more%0ACaused+by%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fservices%2Fapis%2Fcrms%2Fdynamics%2FWebhooks.ts%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fservices%2Fapis%2Fcrms%2Fdynamics%2FWebhooks.ts%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagen...%0A%60%60%60

### Additional context

_No response_

### LINKED ISSUE #2315: Crash
### IDE Information

Latest Idea, Cody 7.0.4-nightly

### Bug Description

The IDE opened a url which was too long for github to parse:

https://github.com/sourcegraph/jetbrains/issues/new?template=bug_report.yml&labels=bug&projects=sourcegraph/381&title=bug%3A+java.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp...&about=IntelliJ+IDEA+2024.2.1+%28Ultimate+Edition%29%0ABuild+%23IU-242.21829.142%2C+built+on+August+28%2C+2024%0ALicensed+to+Kamil+Burzynski%0ASubscription+is+active+until+October+6%2C+2024.%0ARuntime+version%3A+21.0.3%2B13-b509.11+aarch64+%28JCEF+122.1.9%29%0AVM%3A+OpenJDK+64-Bit+Server+VM+by+JetBrains+s.r.o.%0AToolkit%3A+sun.lwawt.macosx.LWCToolkit%0AmacOS+14.6.1%0AGC%3A+G1+Young+Generation%2C+G1+Concurrent+GC%2C+G1+Old+Generation%0AMemory%3A+16384M%0ACores%3A+10%0AMetal+Rendering+is+ON%0ARegistry%3A%0A++actionSystem.playback.typecommand.delay%3D50%0A++debugger.new.tool.window.layout%3Dtrue%0A++vcs.log.index.enable%3Dtrue%0A++ide.experimental.ui%3Dtrue%0A++i18n.locale%3D%0A++typescript.service.node.arguments%3D--max-old-space-size%3D8192%0A++editor.minimap.enabled%3Dtrue%0A++terminal.new.ui%3Dtrue%0ANon-Bundled+Plugins%3A%0A++com.mroche.JsonHelper+%281.3.2%29%0A++String+Manipulation+%289.14.1%29%0A++com.wakatime.intellij.plugin+%2815.0.3%29%0A++ru.adelf.idea.dotenv+%282024.2.1%29%0A++PlantUML+integration+%287.11.2-IJ2023.2%29%0A++org.jetbrains.plugins.github+%28242.21829.162%29%0A++com.sourcegraph.jetbrains+%287.0.4-nightly%29%0A++commit-prefix-plugin+%281.4.1%29%0A++com.cral.JSONKeyFinder+%282.0.8%29%0A++com.eny.i18n+%282.6.2%29%0AKotlin%3A+242.21829.142-IJ%0A&logs=Stacktrace%3A%0A%60%60%60text%0Ajava.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fwebsite%2Fpublic%2Fimg%2Flogos%2Fhuawei-logo.svg%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fwebsite%2Fpublic%2Fimg%2Flogos%2Fhuawei-logo.svg%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A131739%3A19%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A132652%3A18%0A++++at+runNextTicks+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A60%3A5%29%0A++++at+process.processImmediate+%28node%3Ainternal%2Ftimers%3A449%3A9%29%0A++++at+process.topLevelDomainCallback+%28node%3Adomain%3A160%3A15%29%0A++++at+process.callbackTrampoline+%28node%3Ainternal%2Fasync_hooks%3A128%3A24%29%0A++++at+async+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A131215%3A44%0A%09at+com.intellij.util.ExceptionUtil.rethrow%28ExceptionUtil.java%3A136%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled%28ProgressIndicatorUtils.java%3A399%29%0A%09at+com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation%28CodyFixHighlightPass.kt%3A104%29%0A%09at+com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation%28TextEditorHighlightingPass.java%3A57%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%242%28PassExecutorService.java%3A418%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows%28trace.kt%3A118%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows%28TraceUtil.java%3A36%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%243%28PassExecutorService.java%3A413%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction%28AnyThreadWriteThreadingSupport.kt%3A291%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction%28ApplicationImpl.java%3A965%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%244%28PassExecutorService.java%3A404%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.lambda%24executeProcessUnderProgress%2413%28CoreProgressManager.java%3A660%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun%28CoreProgressManager.java%3A735%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress%28CoreProgressManager.java%3A691%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress%28CoreProgressManager.java%3A659%29%0A%09at+com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress%28ProgressManagerImpl.java%3A79%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.doRun%28PassExecutorService.java%3A403%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%240%28PassExecutorService.java%3A379%29%0A%09at+com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside%28FileTypeManagerImpl.java%3A802%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%241%28PassExecutorService.java%3A379%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader%28AnyThreadWriteThreadingSupport.kt%3A486%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader%28ApplicationImpl.java%3A178%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.run%28PassExecutorService.java%3A377%29%0A%09at+com.intellij.concurrency.JobLauncherImpl%24VoidForkJoinTask%241.exec%28JobLauncherImpl.java%3A190%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinTask.doExec%28ForkJoinTask.java%3A507%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool%24WorkQueue.topLevelExec%28ForkJoinPool.java%3A1491%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.scan%28ForkJoinPool.java%3A2073%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.runWorker%28ForkJoinPool.java%3A2035%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinWorkerThread.run%28ForkJoinWorkerThread.java%3A187%29%0ACaused+by%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fwebsite%2Fpublic%2Fimg%2Flogos%2Fhuawei-logo.svg%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fwebsite%2Fpublic%2Fimg%2Flogos%2Fhuawei-logo.svg%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A131739%3A19%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A132652%3A18%0A++++at+runNextTicks+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A60%3A5%29%0A++++at+process.processImmediate+%28node%3Ainternal%2Ftimers%3A449%3A9%29%0A++++at+process.topLevelDomainCallback+%28node%3Adomain%3A160%3A15%29%0A++++at+process.callbackTrampoline+%28node%3Ainternal%2Fasync_hooks%3A128%3A24%29%0A++++at+async+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A131215%3A44%0A%09at+java.base%2Fjava.util.concurrent.CompletableFuture.reportGet%28CompletableFuture.java%3A396%29%0A%09at+java.base%2Fjava.util.concurrent.CompletableFuture.get%28CompletableFuture.java%3A2096%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled%28ProgressIndicatorUtils.java%3A370%29%0A%09...+27+more%0ACaused+by%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fwebsite%2Fpublic%2Fimg%2Flogos%2Fhuawei-logo.svg%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fwebsite%2Fpublic%2Fimg%2Flogos%2Fhuawei-logo.svg%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegrap...%0A%60%60%60

### Additional context

When I opened 'Find files' typed some filename prefix, and started to quickly go through files by pressing cursor down, this kind of error is basically guaranteed.

### LINKED ISSUE #2361: Crash with too long url
### IDE Information

latest idea, latest cody

### Bug Description

Again, a bug with url too long for github to parse:

https://github.com/sourcegraph/jetbrains/issues/new?template=bug_report.yml&labels=bug&projects=sourcegraph/381&title=bug%3A+java.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp...&about=IntelliJ+IDEA+2024.2.3+%28Ultimate+Edition%29%0ABuild+%23IU-242.23339.11%2C+built+on+September+25%2C+2024%0ALicensed+to+Kamil+Burzynski%0ASubscription+is+active+until+October+6%2C+2024.%0ARuntime+version%3A+21.0.4%2B13-b509.17+aarch64+%28JCEF+122.1.9%29%0AVM%3A+OpenJDK+64-Bit+Server+VM+by+JetBrains+s.r.o.%0AToolkit%3A+sun.lwawt.macosx.LWCToolkit%0AmacOS+14.6.1%0AGC%3A+G1+Young+Generation%2C+G1+Concurrent+GC%2C+G1+Old+Generation%0AMemory%3A+16384M%0ACores%3A+10%0AMetal+Rendering+is+ON%0ARegistry%3A%0A++actionSystem.playback.typecommand.delay%3D50%0A++debugger.new.tool.window.layout%3Dtrue%0A++vcs.log.index.enable%3Dtrue%0A++ide.experimental.ui%3Dtrue%0A++i18n.locale%3D%0A++terminal.new.ui%3Dtrue%0A++editor.minimap.enabled%3Dtrue%0A++typescript.service.node.arguments%3D--max-old-space-size%3D8192%0ANon-Bundled+Plugins%3A%0A++com.mroche.JsonHelper+%281.3.2%29%0A++String+Manipulation+%289.14.1%29%0A++com.wakatime.intellij.plugin+%2815.0.3%29%0A++ru.adelf.idea.dotenv+%282024.2.1%29%0A++PlantUML+integration+%287.11.2-IJ2023.2%29%0A++com.sourcegraph.jetbrains+%287.0.6%29%0A++commit-prefix-plugin+%281.4.1%29%0A++com.cral.JSONKeyFinder+%282.0.8%29%0A++com.eny.i18n+%282.6.2%29%0AKotlin%3A+242.23339.11-IJ%0A&logs=Stacktrace%3A%0A%60%60%60text%0Ajava.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+Aborted%28%29.+Build+with+-sASSERTIONS+for+more+info.%0A%0ARuntimeError%3A+Aborted%28%29.+Build+with+-sASSERTIONS+for+more+info.%0A++++at+abort+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A117977%3A172%29%0A++++at+_abort+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A118460%3A15%29%0A++++at+wasm%3A%2F%2Fwasm%2F000b54aa%3Awasm-function%5B134%5D%3A0x1c350%0A++++at+wasm%3A%2F%2Fwasm%2F000b54aa%3Awasm-function%5B172%5D%3A0x1e16b%0A++++at+Query.captures+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A119625%3A36%29%0A++++at+Object.getTestableNode+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A119849%3A59%29%0A++++at+execQueryWrapper+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A119992%3A50%29%0A++++at+TestCodeAction.provideCodeActions+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A235815%3A32%29%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128789%3A44%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A129744%3A18%0A++++at+async+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128268%3A44%0A%09at+com.intellij.util.ExceptionUtil.rethrow%28ExceptionUtil.java%3A136%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled%28ProgressIndicatorUtils.java%3A399%29%0A%09at+com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation%28CodyFixHighlightPass.kt%3A104%29%0A%09at+com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation%28TextEditorHighlightingPass.java%3A67%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%242%28PassExecutorService.java%3A431%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows%28trace.kt%3A118%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows%28TraceUtil.java%3A36%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%243%28PassExecutorService.java%3A426%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction%28AnyThreadWriteThreadingSupport.kt%3A291%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction%28ApplicationImpl.java%3A965%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%244%28PassExecutorService.java%3A417%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.lambda%24executeProcessUnderProgress%2413%28CoreProgressManager.java%3A660%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun%28CoreProgressManager.java%3A735%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress%28CoreProgressManager.java%3A691%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress%28CoreProgressManager.java%3A659%29%0A%09at+com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress%28ProgressManagerImpl.java%3A79%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.doRun%28PassExecutorService.java%3A416%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%240%28PassExecutorService.java%3A392%29%0A%09at+com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside%28FileTypeManagerImpl.java%3A802%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%241%28PassExecutorService.java%3A392%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader%28AnyThreadWriteThreadingSupport.kt%3A486%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader%28ApplicationImpl.java%3A178%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.run%28PassExecutorService.java%3A390%29%0A%09at+com.intellij.concurrency.JobLauncherImpl%24VoidForkJoinTask%241.exec%28JobLauncherImpl.java%3A259%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinTask.doExec%28ForkJoinTask.java%3A507%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool%24WorkQueue.topLevelExec%28ForkJoinPool.java%3A1491%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.scan%28ForkJoinPool.java%3A2073%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.runWorker%28ForkJoinPool.java%3A2035%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinWorkerThread.run%28ForkJoinWorkerThread.java%3A187%29%0ACaused+by%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+Aborted%28%29.+Build+with+-sASSERTIONS+for+more+info.%0A%0ARuntimeError%3A+Aborted%28%29.+Build+with+-sASSERTIONS+for+more+info.%0A++++at+abort+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A117977%3A172%29%0A++++at+_abort+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A118460%3A15%29%0A++++at+wasm%3A%2F%2Fwasm%2F000b54aa%3Awasm-function%5B134%5D%3A0x1c350%0A++++at+wasm%3A%2F%2Fwasm%2F000b54aa%3Awasm-function%5B172%5D%3A0x1e16b%0A++++at+Query.captures+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A119625%3A36%29%0A++++at+Object.getTestableNode+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A119849%3A59%29%0A++++at+execQueryWrapper+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A119992%3A50%29%0A++++at+TestCodeAction.provideCodeActions+%28%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A235815%3A32%29%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FInt...%0A%60%60%60

### Additional context

_No response_

### LINKED ISSUE #2402: Crash with long url
### IDE Information

Latest Idea

### Bug Description

https://github.com/sourcegraph/jetbrains/issues/new?template=bug_report.yml&labels=bug&projects=sourcegraph/381&title=bug%3A+com.intellij.serviceContainer.AlreadyDisposedException%3A+Container+is+already+disposed&about=IntelliJ+IDEA+2024.2.3+%28Ultimate+Edition%29%0ABuild+%23IU-242.23339.11%2C+built+on+September+25%2C+2024%0ALicensed+to+Kamil+Burzynski%0AYou+have+a+perpetual+fallback+license+for+this+version.%0ASubscription+is+active+until+October+6%2C+2025.%0ARuntime+version%3A+21.0.4%2B13-b509.17+aarch64+%28JCEF+122.1.9%29%0AVM%3A+OpenJDK+64-Bit+Server+VM+by+JetBrains+s.r.o.%0AToolkit%3A+sun.lwawt.macosx.LWCToolkit%0AmacOS+14.6.1%0AGC%3A+G1+Young+Generation%2C+G1+Concurrent+GC%2C+G1+Old+Generation%0AMemory%3A+16384M%0ACores%3A+10%0AMetal+Rendering+is+ON%0ARegistry%3A%0A++actionSystem.playback.typecommand.delay%3D50%0A++debugger.new.tool.window.layout%3Dtrue%0A++vcs.log.index.enable%3Dtrue%0A++ide.experimental.ui%3Dtrue%0A++i18n.locale%3D%0A++typescript.service.node.arguments%3D--max-old-space-size%3D8192%0A++terminal.new.ui%3Dtrue%0A++editor.minimap.enabled%3Dtrue%0ANon-Bundled+Plugins%3A%0A++com.mroche.JsonHelper+%281.3.2%29%0A++String+Manipulation+%289.14.1%29%0A++com.wakatime.intellij.plugin+%2815.0.3%29%0A++ru.adelf.idea.dotenv+%282024.2.1%29%0A++PlantUML+integration+%287.11.2-IJ2023.2%29%0A++com.sourcegraph.jetbrains+%287.0.6%29%0A++commit-prefix-plugin+%281.4.1%29%0A++com.cral.JSONKeyFinder+%282.0.8%29%0A++com.eny.i18n+%282.6.2%29%0AKotlin%3A+242.23339.11-IJ%0A&logs=Stacktrace%3A%0A%60%60%60text%0Acom.intellij.serviceContainer.AlreadyDisposedException%3A+Container+is+already+disposed%0A%09at+com.intellij.serviceContainer.ComponentManagerImplKt.throwAlreadyDisposedIfNotUnderIndicatorOrJob%28ComponentManagerImpl.kt%3A1672%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImplKt.access%24throwAlreadyDisposedIfNotUnderIndicatorOrJob%28ComponentManagerImpl.kt%3A1%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImpl.doGetService%28ComponentManagerImpl.kt%3A716%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImpl.getService%28ComponentManagerImpl.kt%3A690%29%0A%09at+com.sourcegraph.cody.agent.CodyAgentService%24Companion.getInstance%28CodyAgentService.kt%3A227%29%0A%09at+com.sourcegraph.cody.agent.CodyAgentService%24Companion.withAgent%24lambda%242%28CodyAgentService.kt%3A191%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport%24executeOnPooledThread%241.run%28AnyThreadWriteThreadingSupport.kt%3A134%29%0A%09at+java.base%2Fjava.util.concurrent.Executors%24RunnableAdapter.call%28Executors.java%3A572%29%0A%09at+com.intellij.util.concurrency.ContextCallable.call%28ContextCallable.java%3A32%29%0A%09at+java.base%2Fjava.util.concurrent.FutureTask.run%28FutureTask.java%3A317%29%0A%09at+com.intellij.util.concurrency.ContextRunnable.run%28ContextRunnable.java%3A27%29%0A%09at+java.base%2Fjava.util.concurrent.ThreadPoolExecutor.runWorker%28ThreadPoolExecutor.java%3A1144%29%0A%09at+java.base%2Fjava.util.concurrent.ThreadPoolExecutor%24Worker.run%28ThreadPoolExecutor.java%3A642%29%0A%09at+java.base%2Fjava.util.concurrent.Executors%24PrivilegedThreadFactory%241%241.run%28Executors.java%3A735%29%0A%09at+java.base%2Fjava.util.concurrent.Executors%24PrivilegedThreadFactory%241%241.run%28Executors.java%3A732%29%0A%09at+java.base%2Fjava.security.AccessController.doPrivileged%28AccessController.java%3A400%29%0A%09at+java.base%2Fjava.util.concurrent.Executors%24PrivilegedThreadFactory%241.run%28Executors.java%3A732%29%0A%09at+java.base%2Fjava.lang.Thread.run%28Thread.java%3A1583%29%0ACaused+by%3A+com.intellij.platform.instanceContainer.internal.ContainerDisposedException%3A+Container+%27ProjectImpl%40510022545+services%27+was+disposed%0A%09at+com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.state%28InstanceContainerImpl.kt%3A60%29%0A%09at+com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.state%28InstanceContainerImpl.kt%3A40%29%0A%09at+com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.getInstanceHolder%28InstanceContainerImpl.kt%3A277%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImpl.doGetService%28ComponentManagerImpl.kt%3A712%29%0A%09...+15+more%0ACaused+by%3A+com.intellij.platform.instanceContainer.internal.DisposalTrace%0A%09at+com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.dispose%28InstanceContainerImpl.kt%3A266%29%0A%09at+com.intellij.serviceContainer.ComponentManagerImpl.dispose%28ComponentManagerImpl.kt%3A1164%29%0A%09at+com.intellij.openapi.project.impl.ProjectImpl.dispose%28ProjectImpl.kt%3A321%29%0A%09at+com.intellij.openapi.util.ObjectTree.runWithTrace%28ObjectTree.java%3A131%29%0A%09at+com.intellij.openapi.util.ObjectTree.executeAll%28ObjectTree.java%3A163%29%0A%09at+com.intellij.openapi.util.Disposer.dispose%28Disposer.java%3A205%29%0A%09at+com.intellij.openapi.util.Disposer.dispose%28Disposer.java%3A193%29%0A%09at+com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject%24lambda%2415%28ProjectManagerImpl.kt%3A423%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%24lambda%244%28AnyThreadWriteThreadingSupport.kt%3A318%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%28AnyThreadWriteThreadingSupport.kt%3A328%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%28AnyThreadWriteThreadingSupport.kt%3A318%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction%28ApplicationImpl.java%3A890%29%0A%09at+com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject%28ProjectManagerImpl.kt%3A406%29%0A%09at+com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject%24default%28ProjectManagerImpl.kt%3A328%29%0A%09at+com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose%28ProjectManagerImpl.kt%3A435%29%0A%09at+com.intellij.openapi.wm.impl.CloseProjectWindowHelper.closeProjectAndShowWelcomeFrameIfNoProjectOpened%28CloseProjectWindowHelper.kt%3A57%29%0A%09at+com.intellij.openapi.wm.impl.CloseProjectWindowHelper.windowClosing%28CloseProjectWindowHelper.kt%3A44%29%0A%09at+com.intellij.openapi.wm.impl.ProjectFrameHelper.windowClosing%28ProjectFrameHelper.kt%3A428%29%0A%09at+com.intellij.openapi.wm.impl.WindowCloseListener.windowClosing%28ProjectFrameHelper.kt%3A451%29%0A%09at+java.desktop%2Fjava.awt.AWTEventMulticaster.windowClosing%28AWTEventMulticaster.java%3A357%29%0A%09at+java.desktop%2Fjava.awt.AWTEventMulticaster.windowClosing%28AWTEventMulticaster.java%3A357%29%0A%09at+java.desktop%2Fjava.awt.AWTEventMulticaster.windowClosing%28AWTEventMulticaster.java%3A357%29%0A%09at+java.desktop%2Fjava.awt.AWTEventMulticaster.windowClosing%28AWTEventMulticaster.java%3A357%29%0A%09at+java.desktop%2Fjava.awt.AWTEventMulticaster.windowClosing%28AWTEventMulticaster.java%3A357%29%0A%09at+java.desktop%2Fjava.awt.Window.processWindowEvent%28Window.java%3A2115%29%0A%09at+java.desktop%2Fjavax.swing.JFrame.processWindowEvent%28JFrame.java%3A298%29%0A%09at+java.desktop%2Fjava.awt.Window.processEvent%28Window.java%3A2074%29%0A%09at+java.desktop%2Fjava.awt.Component.dispatchEventImpl%28Component.java%3A5035%29%0A%09at+java.desktop%2Fjava.awt.Container.dispatchEventImpl%28Container.java%3A2324%29%0A%09at+java.desktop%2Fjava.awt.Window.dispatchEventImpl%28Window.java%3A2810%29%0A%09at+java.desktop%2Fjava.awt.Component.dispatchEvent%28Component.java%3A4860%29%0A%09at+java.desktop%2Fjava.awt.EventQueue.dispatchEventImpl%28EventQueue.java%3A783%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%244.run%28EventQueue.java%3A728%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%244.run%28EventQueue.java%3A722%29%0A%09at+java.base%2Fjava.security.AccessController.doPrivileged%28AccessController.java%3A400%29%0A%09at+java.base%2Fjava.security.ProtectionDomain%24JavaSecurityAccessImpl.doIntersectionPrivilege%28ProtectionDomain.java%3A87%29%0A%09at+java.base%2Fjava.security.ProtectionDomain%24JavaSecurityAccessImpl.doIntersectionPrivilege%28ProtectionDomain.java%3A98%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%245.run%28EventQueue.java%3A755%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%245.run%28EventQueue.java%3A753%29%0A%09at+java.base%2Fjava.se...%0A%60%60%60

### Additional context

_No response_

### LINKED ISSUE #2420: Crash with too long url
### IDE Information

Latest IDea

### Bug Description

I closed all files and then pressed cmd-shift-O to search for files. Crash happened immediately after find file dialog popped up.

https://github.com/sourcegraph/jetbrains/issues/new?template=bug_report.yml&labels=bug&projects=sourcegraph/381&title=bug%3A+java.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp...&about=IntelliJ+IDEA+2024.2.3+%28Ultimate+Edition%29%0ABuild+%23IU-242.23339.11%2C+built+on+September+25%2C+2024%0ALicensed+to+Kamil+Burzynski%0AYou+have+a+perpetual+fallback+license+for+this+version.%0ASubscription+is+active+until+October+6%2C+2025.%0ARuntime+version%3A+21.0.4%2B13-b509.17+aarch64+%28JCEF+122.1.9%29%0AVM%3A+OpenJDK+64-Bit+Server+VM+by+JetBrains+s.r.o.%0AToolkit%3A+sun.lwawt.macosx.LWCToolkit%0AmacOS+14.6.1%0AGC%3A+G1+Young+Generation%2C+G1+Concurrent+GC%2C+G1+Old+Generation%0AMemory%3A+16384M%0ACores%3A+10%0AMetal+Rendering+is+ON%0ARegistry%3A%0A++actionSystem.playback.typecommand.delay%3D50%0A++debugger.new.tool.window.layout%3Dtrue%0A++vcs.log.index.enable%3Dtrue%0A++ide.experimental.ui%3Dtrue%0A++i18n.locale%3D%0A++typescript.service.node.arguments%3D--max-old-space-size%3D8192%0A++terminal.new.ui%3Dtrue%0A++editor.minimap.enabled%3Dtrue%0ANon-Bundled+Plugins%3A%0A++com.mroche.JsonHelper+%281.3.2%29%0A++String+Manipulation+%289.14.1%29%0A++com.wakatime.intellij.plugin+%2815.0.3%29%0A++ru.adelf.idea.dotenv+%282024.2.1%29%0A++PlantUML+integration+%287.11.2-IJ2023.2%29%0A++com.sourcegraph.jetbrains+%287.0.6%29%0A++commit-prefix-plugin+%281.4.1%29%0A++com.cral.JSONKeyFinder+%282.0.8%29%0A++com.eny.i18n+%282.6.2%29%0AKotlin%3A+242.23339.11-IJ%0A&logs=Stacktrace%3A%0A%60%60%60text%0Ajava.lang.RuntimeException%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fworker%2Fdebug.ts%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fworker%2Fdebug.ts%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128784%3A19%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A129744%3A18%0A++++at+runNextTicks+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A60%3A5%29%0A++++at+process.processImmediate+%28node%3Ainternal%2Ftimers%3A449%3A9%29%0A++++at+process.topLevelDomainCallback+%28node%3Adomain%3A160%3A15%29%0A++++at+process.callbackTrampoline+%28node%3Ainternal%2Fasync_hooks%3A128%3A24%29%0A++++at+async+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128268%3A44%0A%09at+com.intellij.util.ExceptionUtil.rethrow%28ExceptionUtil.java%3A136%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled%28ProgressIndicatorUtils.java%3A399%29%0A%09at+com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation%28CodyFixHighlightPass.kt%3A104%29%0A%09at+com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation%28TextEditorHighlightingPass.java%3A67%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%242%28PassExecutorService.java%3A431%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows%28trace.kt%3A118%29%0A%09at+com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows%28TraceUtil.java%3A36%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%243%28PassExecutorService.java%3A426%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction%28AnyThreadWriteThreadingSupport.kt%3A291%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction%28ApplicationImpl.java%3A965%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24doRun%244%28PassExecutorService.java%3A417%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.lambda%24executeProcessUnderProgress%2413%28CoreProgressManager.java%3A660%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun%28CoreProgressManager.java%3A735%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress%28CoreProgressManager.java%3A691%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress%28CoreProgressManager.java%3A659%29%0A%09at+com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress%28ProgressManagerImpl.java%3A79%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.doRun%28PassExecutorService.java%3A416%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%240%28PassExecutorService.java%3A392%29%0A%09at+com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside%28FileTypeManagerImpl.java%3A802%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.lambda%24run%241%28PassExecutorService.java%3A392%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader%28AnyThreadWriteThreadingSupport.kt%3A486%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader%28ApplicationImpl.java%3A178%29%0A%09at+com.intellij.codeInsight.daemon.impl.PassExecutorService%24ScheduledPass.run%28PassExecutorService.java%3A390%29%0A%09at+com.intellij.concurrency.JobLauncherImpl%24VoidForkJoinTask%241.exec%28JobLauncherImpl.java%3A259%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinTask.doExec%28ForkJoinTask.java%3A507%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool%24WorkQueue.topLevelExec%28ForkJoinPool.java%3A1491%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.scan%28ForkJoinPool.java%3A2073%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinPool.runWorker%28ForkJoinPool.java%3A2035%29%0A%09at+java.base%2Fjava.util.concurrent.ForkJoinWorkerThread.run%28ForkJoinWorkerThread.java%3A187%29%0ACaused+by%3A+java.util.concurrent.ExecutionException%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fworker%2Fdebug.ts%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fworker%2Fdebug.ts%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128784%3A19%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A129744%3A18%0A++++at+runNextTicks+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A60%3A5%29%0A++++at+process.processImmediate+%28node%3Ainternal%2Ftimers%3A449%3A9%29%0A++++at+process.topLevelDomainCallback+%28node%3Adomain%3A160%3A15%29%0A++++at+process.callbackTrampoline+%28node%3Ainternal%2Fasync_hooks%3A128%3A24%29%0A++++at+async+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128268%3A44%0A%09at+java.base%2Fjava.util.concurrent.CompletableFuture.reportGet%28CompletableFuture.java%3A396%29%0A%09at+java.base%2Fjava.util.concurrent.CompletableFuture.get%28CompletableFuture.java%3A2096%29%0A%09at+com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled%28ProgressIndicatorUtils.java%3A370%29%0A%09...+27+more%0ACaused+by%3A+java.util.concurrent.ExecutionException%3A+org.eclipse.lsp4j.jsonrpc.ResponseErrorException%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fworker%2Fdebug.ts%0A%0AError%3A+codeActions%2Fprovide%3A+document+not+found+for+file%3A%2F%2F%2FUsers%2Fnopik%2FWarsztat%2Fsunvoy%2Fapp%2Fpackages%2Fworker%2Fdebug.ts%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A128784%3A19%0A++++at+%2FUsers%2Fnopik%2FLibrary%2FApplication+Support%2FJetBrains%2FIntelliJIdea2024.2%2Fplugins%2FSourcegraph%2Fagent%2Findex.js%3A129744%3A18%0A+...%0A%60%60%60

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/2420.
Fixes https://github.com/sourcegraph/jetbrains/issues/2402.
Fixes https://github.com/sourcegraph/jetbrains/issues/2361.
Fixes https://github.com/sourcegraph/jetbrains/issues/2268.
Fixes https://github.com/sourcegraph/jetbrains/issues/2315.
Fixes https://github.com/sourcegraph/jetbrains/issues/2231.

## Test plan
1. When the plugin encounters an error, report it with to GitHub Issues.

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/error/CodyErrorSubmitter.kt [hunk 1]
```diff
@@ -46,13 +47,22 @@ class CodyErrorSubmitter : ErrorReportSubmitter() {
...
+        "https://github.com/sourcegraph/jetbrains/issues/new" +
+            "?template=bug_report.yml" +
+            "&labels=bug" +
+            "&projects=sourcegraph/381"
+
+    val title = throwableText?.let { "&title=${encode(getTitle(it))}" } ?: ""
+    val text = getAboutText(project).get()
+    val about = "&about=${encode(text.repeat(6))}"
+
+    val availableSpace =
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/error/CodyErrorSubmitter.kt:60]: It is impossible to be negative? :)

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/error/CodyErrorSubmitter.kt (hunk 1 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/error/CodyErrorSubmitter.kt:60]: it is but it would require to have probably over 500 plugin installed (so that you IDE Information gets really big)
