### PR TITLE
Fix getRelativePathToProjectRoot call (fixes #246)

### LINKED ISSUE #246: bug: Slow operations are prohibited on EDT (`getRelativePathToProjectRoot`)
### Installation Information

The error appeared to me on IDE start-up. I have seen a noticeable UI freeze. The freeze could be caused by [the other issue](https://github.com/sourcegraph/jetbrains/issues/247) or the Kotlin plugin (which happened to throw a similar error too).

IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 12, 2023
Licensed to Virtus Lab sp. z o.o. / Mikołaj Kondratek
Subscription is active until November 30, 2024.
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
  DevKit (233.11799.300)
  nl.rubensten.texifyidea (0.9.2)
  com.virtuslab.git-machete (4.1.1-27-SNAPSHOT+git.6ba3ca9-dirty)
  com.sourcegraph.jetbrains (5.2.15221-nightly)
Kotlin: 233.11799.300-IJ

### Describe the bug

```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:101)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:130)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:75)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:247)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:230)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:147)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:141)
	at com.sourcegraph.common.ProjectFileUtils.getRelativePathToProjectRoot(ProjectFileUtils.kt:10)
	at com.sourcegraph.cody.context.CurrentlyOpenFileListener.selectionChanged$lambda$0(CurrentlyOpenFileListener.kt:20)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.sourcegraph.cody.context.CurrentlyOpenFileListener.selectionChanged(CurrentlyOpenFileListener.kt:14)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:664)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy1/jdk.proxy1.$Proxy63.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.kt:1754)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$fireSelectionChanged(FileEditorManagerImpl.kt:126)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1$1$1.invoke(FileEditorManagerImpl.kt:240)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1$1$1.invoke(FileEditorManagerImpl.kt:238)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1$1.invokeSuspend(FileEditorManagerImpl.kt:238)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1430)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Expected behavior

no error

### Additional context (logs, images, etc)

_No response_

### PR DESCRIPTION
**Pull request by mkondratek**
## Test plan
- install the plugin built from these changes on IntelliJ 2023.2 (or 2023.3)
- the error should not appear 

(alternatively runIde against this version of IDE)

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentCodebase.kt [hunk 1]
```diff
@@ -35,9 +35,11 @@ class CodyAgentCodebase(private val underlying: CodyAgentServer, private val pro
       application.runReadAction {
         val openedFileName = file.name
         val relativeFilePath: String? = ProjectFileUtils.getRelativePathToProjectRoot(project, file)
-        CodyToolWindowContent.getInstance(project)
-            .embeddingStatusView
-            .setOpenedFileName(openedFileName, relativeFilePath)
+        ApplicationManager.getApplication().invokeLater {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentCodebase.kt:38]: ui actions should be called from ui thread

File: src/main/kotlin/com/sourcegraph/cody/context/CurrentlyOpenFileListener.kt [hunk 2]
```diff
@@ -11,15 +11,18 @@ class CurrentlyOpenFileListener(
...
+    val openedFileName = newFile?.name ?: ""
+    var relativeFilePath: String? = null
 
+    ApplicationManager.getApplication().executeOnPooledThread {
       if (newFile != null) {
         relativeFilePath = ProjectFileUtils.getRelativePathToProjectRoot(project, newFile)
       }
-      embeddingStatusView.setOpenedFileName(openedFileName, relativeFilePath)
+
+      ApplicationManager.getApplication().invokeLater {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/context/CurrentlyOpenFileListener.kt:23]: ui actions should be called from ui thread

File: src/main/kotlin/com/sourcegraph/cody/context/CurrentlyOpenFileListener.kt [hunk 3]
```diff
@@ -11,15 +11,18 @@ class CurrentlyOpenFileListener(
     private val embeddingStatusView: EmbeddingStatusView
 ) : FileEditorManagerListener {
   override fun selectionChanged(event: FileEditorManagerEvent) {
-    ApplicationManager.getApplication().runReadAction {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/context/CurrentlyOpenFileListener.kt:14]: for some reason wrapping it here did not help, I moved `runReadAction` closer to the place we need it

File: src/main/kotlin/com/sourcegraph/cody/context/CurrentlyOpenFileListener.kt (hunk 2 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/context/CurrentlyOpenFileListener.kt:23]: Cannot that whole code be simplified to just that?

```kotlin
val newFile = event.newFile
ApplicationManager.getApplication().executeOnPooledThread {
  if (newFile?.name) {
    val relativeFilePath = ProjectFileUtils.getRelativePathToProjectRoot(project, newFile)
    ApplicationManager.getApplication().invokeLater {
      embeddingStatusView.setOpenedFileName(newFile.name, relativeFilePath)
    }
  }
}
```

**Review by pkukielka — APPROVED** [review]
LGTM
