### PR TITLE
Fix commands for selection after IDE restart

### LINKED ISSUE #58160: JetBrains: commands stuck on "Generating" on IDE startup/restart
## Installation information
- IntelliJ IDEA 2023.2.4 (as well as Android Studio and likely others)
- Sourcegraph Cody + Code Search Plugin 5.2.4819

## Steps to reproduce
Approach 1:
- Highlight some text
- Restart IDE
- Without clicking in the text editor section (aka keeping the originally highlighted code selected), attempt to run a Command

Approach 2:
- Dont highlight text (aka have text cursor in some position X)
- Restart IDE
- Without moving the cursor (aka dont click in the text editor section except for position X), attempt to run a Command

## Expected behavior
The command works as expected

## Observed behavior
The chat panel is stuck on "Generating". Further chat messages work as expected, but Commands dont until text is either re-selected or the cursor is moved

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/sourcegraph/issues/58160.

## Test plan

Approach 1:
1. Highlight some text
2. Restart IDE
3. Without clicking in the text editor section (aka keeping the originally highlighted code selected), attempt to run a Command

Approach 2:
1. Dont highlight text (aka have text cursor in some position X)
2. Restart IDE
3. Without moving the cursor (aka dont click in the text editor section except for position X), attempt to run a Command
image

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt [hunk 1]
```diff
@@ -250,6 +252,9 @@ class CodyToolWindowContent(private val project: Project) : UpdatableChat {
       val recipeButton = createRecipeButton(recipe.title)
       recipeButton.addActionListener {
         GraphQlLogger.logCodyEvent(project, "recipe:" + recipe.id, "clicked")
+        val editorManager = FileEditorManager.getInstance(project)
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt:255]: I simply added this call here - close to the action

Comment (Strum355) [reply src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt:255]: Could you explain why this is needed for this particular bug? Just as someone (me) who doesnt know the why on it, and for looking back on this issue + fix :slightly_smiling_face:

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt:255]: The problem is looks like this:

1. IDE restarts
2. Agent gets up (initalising)
3. a few listeners (e.g. `editorCreated`) are called. however,
4. agnet is not yet connected!
5. `informAgentAboutEditorChange` ends at the connections check, `TextDocument` is not updated

See [isConnected](https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/blob/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt?L187)
See [informAgentAboutEditorChange](https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/blob/src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyEditorFactoryListener.kt?L147%3A9-147%3A37) and it's invocations 

is it clear to you? I can give more details if you need

**Review by Strum355 — APPROVED** [review]

**Review by Sa1to — APPROVED** [review]
LGTM :)

**Review by exigow — APPROVED** [review]

**Comment by exigow** [comment]
I tested it and indeed it's fixed. :+1:
