### PR TITLE
Convert server url to lowercase

### LINKED ISSUE #928: JetBrains: Free tier users can access Enterprise tier features.
### Installation Information

Plugin version: `5.3.2625-nightly`
IDE version: `PC-233.13763.11`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains PyCharm editor
2. Click on "Sign in with an Enterprise Instance"
3. Enter server as "SOURCEGRAPH.COM" and your Token
4. Hit "Sign in" button

**Observed behavior:**
Check the Cody window, there is a Add remote repo button available. Also, the LLM is disabled and "Account" tab is not there.

### Expected behavior

There should be a validation to gate free users from accessing Enterprise features.

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1bvc0x7e4U4v-Xr4G5tuV7ogQ-ReNiAlR/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes #928.

## Test plan
1. see the issue ☝️

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/config/CodyAccount.kt [hunk 1]
```diff
@@ -29,7 +29,7 @@ data class CodyAccount(
     return AccountType.ENTERPRISE
   }
 
-  fun isDotcomAccount() = server.url.startsWith(ConfigUtil.DOTCOM_URL)
+  fun isDotcomAccount() = server.url.lowercase().startsWith(ConfigUtil.DOTCOM_URL)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/CodyAccount.kt:32]: Maybe we should just lowercase getter?
Anyway, that is fine for me.

**Review by pkukielka — APPROVED** [review]
LGTM
