### PR TITLE
Properly set taskId right after we receive it (fixes cancel)

### LINKED ISSUE #1414: JetBrains: Crash occurred when user cancels the "Generate Unit Test" process with "bug: com.intellij.util.IncorrectOperationException: Sorry but parent: com.sourcegraph.cody.edit.sessions.TestCodeSession@2774cde2 ..." error
### Cody Version

v5.5.7-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.7-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with PRO user
3. Open any source code file
4. Select any code snippet and go to "Cody > Generate Unit Test"
5. Click on "Cancel" button before Cody generate the unit test
6. Wait for some time

### Observed behavior:
Crash occurred with following stacktrace,
Stacktrace:
```text
com.intellij.util.IncorrectOperationException: Sorry but parent: com.sourcegraph.cody.edit.sessions.TestCodeSession@2774cde2 (class com.sourcegraph.cody.edit.sessions.TestCodeSession) has already been disposed (see the cause for stacktrace) so the child: LensWidgetGroup: {} (class com.sourcegraph.cody.edit.widget.LensWidgetGroup) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:161)
	at com.sourcegraph.cody.edit.widget.LensWidgetGroup.<init>(LensWidgetGroup.kt:99)
	at com.sourcegraph.cody.edit.widget.LensGroupFactory.createTaskWorkingGroup(LensGroupFactory.kt:13)
	at com.sourcegraph.cody.edit.sessions.FixupSession.showWorkingGroup(FixupSession.kt:201)
	at com.sourcegraph.cody.edit.sessions.FixupSession.createAndSwitchFileIfNeeded$lambda$14$lambda$13(FixupSession.kt:338)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

### Expected behavior

Crash should not occur and the process should be cancelled successfully.

### Additional context

**Video link:**

https://drive.google.com/file/d/1OFM8pVrhyrSmDeAV-C972uHCRXi9fFq1/view?usp=drive_link

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/1414

## Changes

With that change we set the `taskId` as early as possible, without bigger refactor on the agent side.
That fixes e.g. `Cancel` option, which previously was sent mostly with a `null` `taskId` and thus was not working.

## Test plan

Manual verification that cancel now works in Jetbrains

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt [hunk 1]
```diff
@@ -107,7 +107,6 @@ abstract class FixupSession(
             if (error != null || result == null) {
               showErrorGroup("Error while generating doc string: $error")
             } else {
-              taskId = result.id
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt:110]: That was happening too late

**Review by odisseus — APPROVED** [review]
