### PR TITLE
Fix wrong line error (fixes #1629)

### LINKED ISSUE #1629: bug: java.lang.IndexOutOfBoundsException: Wrong line: 22. Available lines count: 22
Cody 5.5.14
Windows 11

---

image

image

```
2024-05-24 14:54:17,962 [ 505099] SEVERE - #c.i.i.p.PluginManager - Wrong line: 22. Available lines count: 22
java.lang.IndexOutOfBoundsException: Wrong line: 22. Available lines count: 22
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineEnd(LineSet.java:194)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineEndOffset(DocumentImpl.java:1028)
	at com.sourcegraph.cody.agent.protocol.ProtocolTextDocument$Companion.getVisibleRange(ProtocolTextDocument.kt:52)
	at com.sourcegraph.cody.agent.protocol.ProtocolTextDocument$Companion.fromVirtualFile(ProtocolTextDocument.kt:90)
	at com.sourcegraph.cody.agent.protocol.ProtocolTextDocument$Companion.fromEditor(ProtocolTextDocument.kt:77)
	at com.sourcegraph.cody.listeners.CodyFocusChangeListener.focusGained(CodyFocusChangeListener.kt:19)
	at com.intellij.openapi.editor.ex.FocusChangeListener.focusGained(FocusChangeListener.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy102.focusGained(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorImpl.fireFocusGained(EditorImpl.java:1327)
	at com.intellij.openapi.editor.impl.EditorImpl.focusGained(EditorImpl.java:571)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.Component.processFocusEvent(Component.java:6543)
	at java.desktop/java.awt.Component.processEvent(Component.java:6410)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1061)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:680)
	at com.intellij.ide.IdeKeyboardFocusManager.lambda$dispatchEvent$0(IdeKeyboardFocusManager.java:44)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:44)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4910)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/sun.awt.SunToolkit$1.run(SunToolkit.java:511)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
```

---

Steps:
just open a project and switch to the file

### PR DESCRIPTION
**Pull request by mkondratek**
## Test plan

See the issue: #1629

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt [hunk 1]
```diff
@@ -48,7 +48,7 @@ private constructor(
       val startOffsetColumn = max(startOffset.column, 0)
 
       val endOffset = editor.xyToLogicalPosition(Point(visibleArea.right, visibleArea.bottom))
-      val endOffsetLine = max(0, min(endOffset.line, editor.document.lineCount))
+      val endOffsetLine = max(0, min(endOffset.line, editor.document.lineCount - 1))
```
Comment (odisseus) [inline src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt:51]: This reverts the [changes](https://github.com/sourcegraph/jetbrains/pull/1626/files#diff-c0bb048e18268f186841365d5e966eaff9f89d04f2d3b3ac48544510eadda0fb) which were merged just a few hours ago in #1626. Is this right?

**Review by olafurpg — APPROVED** [review]
Sorry 🙈

**Comment by olafurpg** [comment]
If only we had tests!
