### PR TITLE
Push enhanced context state to the extension when creating an EnhancedContextPanel

### LINKED ISSUE #1347: JetBrains: Adding repo for context will not improve answer and Cody will respond same.
### Cody Version

v5.5.6-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.6-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Open `sourcegraph/cody` project with enterprise account
4. Ask Cody a question "what is squirrel?" and check the response
5. Add `github.com/sourcegraph/sourcegraph` repo for context
6. Ask Cody a question "what is squirrel?" and check the response

### Observed behavior:
There is no improvement observed in Cody response after adding repo. Cody respond with similar answer.
It looks like there is no effect of adding new repo as Cody is still using same context.

### Expected behavior

Cody should use the context from `github.com/sourcegraph/sourcegraph` repo and an HTTP server when asked "what is squirrel?"

### Additional context

**Video link:**

https://drive.google.com/file/d/1STOdyCG91DoURrfZonnyg9Mc-XBz1I10/view?usp=drive_link

### PR DESCRIPTION
**Pull request by dominiccooney**
Fixes #1347

## Test plan

- Open a clone of the sourcegraph repo
- Start a chat, click Pencil, add `github.com/sourcegraph/cody` repo, cmd-enter to commit
- Ask "how do local embeddings work", there should be some context results from the `cody` repo
- Click pencil, add `github.com/sourcegraph/handbook` repo, cmd-enter to commit
- Click "new chat" button
- Ask "what's the role of an engineering manager?", there should be some context results from the `handbook` repo
- Click pencil, delete the handbook repo, cmd-enter to commit
- Ask "what's the role of an engineering manager?", there should be no context results from the `handbook` repo
- Chat history, select the first chat, the repo selector should show the cody and handbook repos
- Chat history, select the second chat, the repo selector should show the cody repo

### CODE REVIEW

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/context/RemoteRepoUtils.kt [hunk 1]
```diff
@@ -32,4 +36,20 @@ object RemoteRepoUtils {
...
+
+  /**
+   * Resolves the repositories named in `repos` and runs `callback` with the first `MAX_REMOTE_REPOSITORY_COUNT` of
+   * them. If remote repo resolution fails, displays an error message instead.
+   */
+  fun resolveReposWithErrorNotification(project: Project, repos: List<CodebaseName>, callback: (List<Repo>) -> Unit): CompletableFuture<Unit> {
+    return getRepositories(project, repos)
+      .completeOnTimeout(null, 15, TimeUnit.SECONDS)
+      .thenApply { resolvedRepos ->
+        if (resolvedRepos == null || (resolvedRepos.isEmpty() && repos.isNotEmpty())) {
```
Comment (odisseus) [inline src/main/kotlin/com/sourcegraph/cody/context/RemoteRepoUtils.kt]: You could make the `repos.isNotEmpty()` check at the very beginning of the method, and skip the rest of the work if it doesn't hold. Also, you could avoid the null check by completing the future with `listOf()` in case of timeout.

Comment (dominiccooney) [reply src/main/kotlin/com/sourcegraph/cody/context/RemoteRepoUtils.kt]: Thanks for the feedback, this is much nicer.
