### PR TITLE
Scroll to the bottom on submit in the chat (fixes #340)

### LINKED ISSUE #340: We should auto-scroll to the bottom when submitting a new message
To reproduce:

- Send message with long reply
- Scroll to the top
- Submit new message
- Notice that you have to manually scroll to the bottom to see the new streaming reply

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes #340

## Test plan
1. having a few messages in the chat (so that it takes the whole height)
2. scroll up (so that the view does not touch the bottom) 
3. send a chat message

Expected:
view goes down and autoscrolls

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/ChatPanel.kt [hunk 1]
```diff
@@ -80,11 +80,15 @@ class ChatPanel(
...
   @RequiresEdt
   fun addOrUpdateMessage(message: ChatMessage, index: Int) {
-    if (messagesPanel.componentCount == 1) {
+    val numberOfMessagesBeforeAddOrUpdate = messagesPanel.componentCount
+    if (numberOfMessagesBeforeAddOrUpdate == 1) {
       llmDropdown.updateAfterFirstMessage()
       promptPanel.updateEmptyTextAfterFirstMessage()
     }
     messagesPanel.addOrUpdateMessage(message, index)
+    if (numberOfMessagesBeforeAddOrUpdate < messagesPanel.componentCount) {
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/chat/ui/ChatPanel.kt:89]: In which situation that if may not evaluate to `true`?

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/chat/ui/ChatPanel.kt:89]: For message update

**Review by pkukielka — APPROVED** [review]
LGTM
