### PR TITLE
Show scratch files in IJ if cody request untitled:// file

### LINKED ISSUE #1493: bug: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
### Cody Version

6e3cd8577afa7cac754ed354a5c2b77ea2ae3ed8

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 12
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

1. Open a project
2. Open a text file outside of the project
3. Write "An interpreter for S-expressions which can do arithmetic.", select it, and Cody, Generate Unit Test (new version)

The CodyAgentService line 80 is getting a URI, `untitled:eb57dd3f-85c0-433e-86a4-05bfe28fe85c.txt`

### Expected behavior

Don't throw.

### Additional context

Stacktrace:

```text
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:67)
 at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
 at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
 at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
 ... 12 more
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: file:
 at java.base/java.net.URI$Parser.fail(URI.java:2913)
 at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
 at java.base/java.net.URI$Parser.parse(URI.java:3119)
 at java.base/java.net.URI.(URI.java:685)
 at com.intellij.util.UriUtilKt.withScheme(UriUtil.kt:16)
 at com.sourcegraph.cody.agent.CodyAgentService$1.invoke$lambda$9(CodyAgentService.kt:80)
 at com.sourcegraph.cody.agent.CodyAgentClient.openUntitledDocument(CodyAgentClient.java:104)
 ... 17 more
 
```

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/1493

## Changes

image

## Test plan

1. Open any random text file from outside the workspace
2. Select some text from it
3. Ask Cody to generate unit tests for it

### CODE REVIEW

**Comment by steveyegge** [comment]
This is so cool! I had no idea all these years that IntelliJ even _allowed_ you to open files outside your workspace. Great fix.

File: src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt [hunk 1]
```diff
@@ -188,18 +193,67 @@ object CodyEditorUtil {
...
+      return LocalFileSystem.getInstance().refreshAndFindFileByNioFile(fixedUri.toPath())
+    } catch (e: URISyntaxException) {
+      // Let's try scratch files
+      val fileName = uriString.substringAfterLast('/').substringAfterLast('\\')
+      return ScratchRootType.getInstance()
+          .findFile(project, fileName, ScratchFileService.Option.existing_only)
+    }
+  }
+
+  fun createFileOrScratch(
```
Comment (steveyegge) [inline src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt:233]: Have you tested this on Windows yet?

**Review by steveyegge — APPROVED** [review]

File: src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt (hunk 1 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt:233]: I've just tried it - it fails with an error 😕 

## Scenario
1. Run `Generate Unit Tests` in a markdown file on Windows

But it does not look like a windows issue. It seems to be a threading problem (pooled thread instead of awt).

```
Access is allowed from event dispatch thread only

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	... 12 more
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[pool-5-thread-1,5,main] 1166554505
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 846922080
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1103)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1086)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:166)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:197)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:85)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:25)
	at com.jetbrains.rdserver.ui.dialogs.BackendDialogWrapperPeerFactory.createPeer(BackendDialogWrapperPeerFactory.kt:51)
	at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:857)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:232)
	at com.intellij.ui.messages.AlertDialog.<init>(AlertMessagesManager.kt:98)
	at com.intellij.ui.messages.AlertMessagesManager.showMessageDialog(AlertMessagesManager.kt:63)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:49)
	at com.jetbrains.rdserver.ui.BackendMessagesService.showMessageDialog(BackendMessagesService.kt:29)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:273)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:289)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:304)
	at com.intellij.openapi.ui.Messages.showMessageDialog(Messages.java:333)
	at com.intellij.ide.scratch.ScratchRootType.createScratchFile(ScratchRootType.java:95)
	at com.sourcegraph.utils.CodyEditorUtil.createFileOrScratch(CodyEditorUtil.kt:251)
	at com.sourcegraph.cody.agent.CodyAgentService$2.invoke$lambda$9(CodyAgentService.kt:115)
	at com.sourcegraph.cody.agent.CodyAgentClient.openUntitledDocument(CodyAgentClient.java:104)
	... 17 more
```
