### PR TITLE
Increasing autocompletion trigger sensitivity

### LINKED ISSUE #57366: JetBrains: automatically trigger autocomplete in specific location
When typing `prompt` in the example from this tweet here, autocomplete doesn't trigger automatically. I have to alt-backslash to get autocomplete loading

 https://x.com/_PabloDev/status/1709725732270751956?s=20

We should fix it so that autocomplete is triggered automatically here. Minimal example to reproduce

```ts
interface DoInteractionRequest {
    chatId: string
    prompt: string
    systemPrompt: string
}

interface Fuzz {
    string: () => string
}

const z: Fuzz = {} as any

const interactionRequest: DoInteractionRequest = {
    chatId_CURSOR_
    prompt: z.string(),
    systemPrompt: z.string(),
}

```

### PR DESCRIPTION
**Pull request by Sa1to**
It fixes [JetBrains: automatically trigger autocomplete in specific location#57366](https://github.com/sourcegraph/sourcegraph/issues/57366) and fixes problem with incorrect serialization of `triggerKind` parameter, sent to the agent + fixing range calculation for lookup manager autocompletion.

## Test plan

* Autocompletion is automatically triggered for this example: 
```
interface DoInteractionRequest {
    chatId: string
    prompt: string
    systemPrompt: string
}

interface Fuzz {
    string: () => string
}

const z: Fuzz = {} as any

const interactionRequest: DoInteractionRequest = {
    chatId_CURSOR_
    prompt: z.string(),
    systemPrompt: z.string(),
}
```

https://github.com/sourcegraph/jetbrains/assets/9321940/9f475127-ada6-4e0b-811d-69cc178f12c5

* Lookup manager autocompletions are correctly triggered

https://github.com/sourcegraph/jetbrains/assets/9321940/2bec91b3-cac5-470e-abee-9b2dc335c282

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt [hunk 1]
```diff
@@ -1,15 +1,13 @@
...
+  INVOKE("Invoke"),
 }
 
 data class AutocompleteParams(
     val filePath: String,
     val position: Position,
-    val triggerKind: AutocompleteTriggerKind? = AutocompleteTriggerKind.AUTOMATIC,
+    val triggerKind: String? = AutocompleteTriggerKind.AUTOMATIC.value,
     val selectedCompletionInfo: SelectedCompletionInfo? = null
 )
```
Comment (Strum355) [inline src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: Are you sure `@SerializedName` doesnt work? I had tested it originally as part of https://github.com/sourcegraph/jetbrains/pull/88/ and it appeared to work fine :thinking: https://stackoverflow.com/questions/16740078/serialize-and-deserialize-enum-with-gson

Comment (Strum355) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: I created a sample project with the following code:
```kotlin
import com.google.gson.Gson
import com.google.gson.annotations.SerializedName

enum class AutocompleteTriggerKind {
    @SerializedName("Automatic") AUTOMATIC,
    @SerializedName("Invoke") INVOKE,
  }

data class User(val firstName: String, val lastName: String, val kind: AutocompleteTriggerKind) {
    val banana: String = ""
}

fun main() {
    val gson = Gson().toJson(User("Tom", "Broody", AutocompleteTriggerKind.AUTOMATIC))
    println(gson)
}
```
which yields the following output
`{"firstName":"Tom","lastName":"Broody","kind":"Automatic","banana":""}`

Comment (Sa1to) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: It isn't mapped correctly on the agent side. It was always converted to value `0` idk why

Comment (Sa1to) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: Screenshot 2023-11-15 at 15 56 45

https://github.com/sourcegraph/jetbrains/assets/9321940/c72c79c4-7988-49fb-b1a6-38a5f0b5f16f

Comment (Sa1to) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: This is on main branch

**Comment by mkondratek** [comment]
It is clearly improved now.

I managed to find an issue with the "actions" that appear in the lookup.

image

Idk, what we should do about it. Do not autocomplete for them (the actions). If it is possible to find out and fix it easily in this PR. But probably we can ignore it for now.

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt (hunk 1 above)
Comment (Strum355) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: Looks like this is the issue :facepalm: https://sourcegraph.com/github.com/eclipse-lsp4j/lsp4j/-/blob/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/adapters/EnumTypeAdapter.java?L53-77

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: Hm, but the serialization on the client side seems to work fine.

I tested it with `SourcegraphApiContentHelper.toJson` (I believe it uses the object mapper that is actually used).

It still can be either an issue with the deserialization on the agent side or some issue that is specific to the logs
 only.

Comment (Strum355) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/AutocompleteParams.kt:13]: lsp4j.jsonrpc uses a different Gson builder with different typadapters set afaik

**Review by Strum355 — APPROVED** [review]

File: src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt [hunk 2]
```diff
@@ -184,6 +201,7 @@ class CodyAutocompleteManager {
       triggerKind: InlineCompletionTriggerKind,
       cancellationToken: CancellationToken,
       lookupString: String?,
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt:203]: I looked quickly into the code. 

It seems that it would be possible to disable autocompletion for some specific lookup elements. Now, we are depending directly on the list's selected values (strings). Instead, we could try to check for a precise `com.intellij.codeInsight.lookup.LookupElement` implementation and decide.

If think that would be a nice improvement, b/c the autocompletions for the actions look a bit dumb 😅 I guess we can provide it later. 

What we have here, LGTM.

**Review by mkondratek — APPROVED** [review]
