### PR TITLE
Fix threading issues with showDocument

### LINKED ISSUE #2151: bug: java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
### IDE Information

IntelliJ IDEA 2024.2.0.2 (Ultimate Edition)
Build #IU-242.20224.419, built on August 19, 2024
Licensed to Virtus Lab sp. z o.o. / Mikołaj Kondratek
Subscription is active until November 30, 2024.
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.5
Kotlin analyzer version: 2.0.20-ij242-29
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.browser.jcef.debug.port=9222
  ide.experimental.ui=true
Non-Bundled Plugins:
  DevKit (242.20224.419)
  nl.rubensten.texifyidea (0.9.7)
  com.virtuslab.git-machete (5.0.1)
  com.sourcegraph.jetbrains (6.0.32-nightly)
  org.intellij.scala (2024.2.20)
  com.intellij.wiremock (242.20224.155)
Kotlin: 242.20224.419-IJ

### Bug Description

The error occurred to me when I tried to Generate Unit Tests.

note:
```
	at com.sourcegraph.cody.agent.CodyAgentClient.textDocument_show$lambda$4(CodyAgentClient.kt:107)
	at com.sourcegraph.cody.agent.CodyAgentClient.acceptOnEventThreadAndGet$lambda$0(CodyAgentClient.kt:56)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
```

### Additional context

Stacktrace:
```text
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:106)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:149)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:94)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:260)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isUnderIgnored(ProjectFileIndexImpl.java:76)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isUnderIgnored(ProjectFileIndexFacade.java:73)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.isExcludedOrIgnored(FileManagerImpl.java:441)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:427)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:431)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:431)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:431)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:431)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:431)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:431)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:431)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:420)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:175)
	at com.intellij.psi.AbstractFileViewProvider.shouldCreatePsi(AbstractFileViewProvider.java:89)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:146)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:102)
	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:185)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:382)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getPsiFile(PsiDocumentManagerBase.java:150)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getPsiFile(PsiDocumentManagerBase.java:99)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.getPsiFile(PsiDocumentManagerImpl.java:62)
	at com.intellij.application.options.CodeStyle.getFacade(CodeStyle.java:541)
	at com.intellij.openapi.editor.impl.LazyRangeMarkerFactoryImpl.lambda$createRangeMarker$1(LazyRangeMarkerFactoryImpl.java:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:228)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:221)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:857)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
	at com.intellij.openapi.editor.impl.LazyRangeMarkerFactoryImpl.createRangeMarker(LazyRangeMarkerFactoryImpl.java:29)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.<init>(OpenFileDescriptor.java:59)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.<init>(OpenFileDescriptor.java:38)
	at com.sourcegraph.utils.CodyEditorUtil.showDocument(CodyEditorUtil.kt:170)
	at com.sourcegraph.cody.agent.CodyAgentClient.textDocument_show$lambda$4(CodyAgentClient.kt:107)
	at com.sourcegraph.cody.agent.CodyAgentClient.acceptOnEventThreadAndGet$lambda$0(CodyAgentClient.kt:56)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEve...
```

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/2151.

The problem was that the descriptors constructor needs to be called in BGT while ::navigate requires EDT. 

## Test plan

A good approach to test it is to verify all code paths. There are three:
1. Context Menu > Generate Unit Tests 
2. Cody Tool Window > Options (...) > Open Cody Settings Editor
3. In the chat ask Cody to generate a file (e.g. "hello world page in html") > Apply (creating a new file)

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt [hunk 1]
```diff
@@ -100,17 +100,20 @@ class CodyAgentClient(private val project: Project, private val webview: NativeW
...
-    }
+    val vf =
+        acceptOnEventThreadAndGet { CodyEditorUtil.findFileOrScratch(project, params.uri) }.get()
+
+    val result =
+        if (vf != null) {
+          val selection = params.options?.selection
+          val preserveFocus = params.options?.preserveFocus
+          CodyEditorUtil.showDocument(project, vf, selection, preserveFocus)
+          true
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt]: We can delate that `true` as it is incorrect, `showDocument` already returns `true` if it succeeded.

File: src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt [hunk 2]
```diff
@@ -166,24 +167,24 @@ object CodyEditorUtil {
...
       preserveFocus: Boolean? = false
   ): Boolean {
     try {
-      if (selection == null) {
-        OpenFileDescriptor(project, vf).navigate(/* requestFocus= */ preserveFocus != true)
-      } else {
-        OpenFileDescriptor(
+      val descriptor =
+          if (selection == null) {
+            OpenFileDescriptor(project, vf)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt:179]: Why that change?

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt (hunk 1 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentClient.kt]: fixed
