### PR TITLE
Fix llm mode selector for pro users

### LINKED ISSUE #1843: JetBrains: Pro user is unable to use few LLMs
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.10-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Check the LLM dropdown

### Observed behavior:
Few LLMs `Claude 3 Opus`, `GPT-4o` and `GPT-4 Turbo` are labeled as `Pro` and clicking on it will redirect user to `/cody/subscription` page

### Expected behavior:
Pro user should have access to all LLMs.

### Additional context

**Video link:**

https://drive.google.com/file/d/1xW7ePnIRE3VG9NeAINc5l2hF40jrPfDh/view?usp=drive_link

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/1843.

Rel to https://github.com/sourcegraph/jetbrains/issues/1839.

## Test plan
1. Log in to a pro account
2. Select a pro llm, e.g. gpt 4o
3. Close the project
4. Reopen the project

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt [hunk 1]
```diff
@@ -65,6 +64,8 @@ class LlmDropdown(
 
     isEnabled = chatModelProviderFromState == null
     isVisible = !isEnterpriseAccount
+    setMaximumRowCount(15)
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt:67]: I think we want to make all models visible at once so free users can easier notice pro models at the bottom (so they have some motivation to convert)

**Review by mkondratek — APPROVED** [review]
