### PR TITLE
Made the AccountTier future nullable to account for the situation when there is no active account.

### LINKED ISSUE #1341: JetBrains: Error occurred on installing Cody with no accounts configured "java.lang.IllegalStateException: No active account"
### Cody Version

v5.5.6-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (5.5.6-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

Steps to reproduce:

1. Install Cody build 5.5.6-nightly with no accounts configured
2. Click on "Restart" when prompted after installing Cody

### Observed behavior:
Error occurred with following stacktrace,
Stacktrace:
```text
java.lang.IllegalStateException: No active account
	at com.sourcegraph.cody.history.HistoryService.getOrCreateActiveAccountEntry(HistoryService.kt:146)
	at com.sourcegraph.cody.history.HistoryService.setDefaultLlm(HistoryService.kt:92)
	at com.sourcegraph.cody.chat.ui.LlmDropdown.setSelectedItem(LlmDropdown.kt:90)
	at com.sourcegraph.cody.chat.ui.LlmDropdown$updateModelsInUI$3.invoke$lambda$3(LlmDropdown.kt:65)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

### Expected behavior

No error should occur when installing Cody with or without any accounts configured.

### Additional context
**Video link:**

https://drive.google.com/file/d/1QwK5O90w3-KnqzWWJbFofqvFF_L0W2d3/view?usp=drive_link

_No response_

### PR DESCRIPTION
**Pull request by odisseus**
Fixes #1341.

## Test plan

Manual, described in the issue

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt [hunk 1]
```diff
@@ -54,6 +54,7 @@ class LlmDropdown(
     models.sortedBy { it.codyProOnly }.forEach(::addItem)
 
     CodyAuthenticationManager.getInstance(project).getActiveAccountTier().thenApply { accountTier ->
+      if (accountTier == null) return@thenApply
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt:57]: don't we have to worry about the other place?

https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fjetbrains&branch=main&file=src%2Fmain%2Fjava%2Fcom%2Fsourcegraph%2Fcody%2FMyAccountTabPanel.kt&start_row=98&start_col=4&end_row=102&end_col=5&editor=JetBrains&version=v5.5.6-nightly

Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt:57]: That part of the code seems to be already null-safe. The `update(accountTier)` function will keep scheduling asynchronous calls to itself, until `getActiveAccountTier()` returns a non-null value.

**P.S.** The AI agreed with my reasoning, even though it took a while to convince it.

**P.P.S.** Maybe I should add a delay here...

File: src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt [hunk 2]
```diff
@@ -80,12 +80,12 @@ class CodyAuthenticationManager(val project: Project) : Disposable {
...
    */
   @CalledInAny
-  private fun getActiveAccountTier(forceRefresh: Boolean): CompletableFuture<AccountTier> {
+  private fun getActiveAccountTier(forceRefresh: Boolean): CompletableFuture<AccountTier?> {
     activeAccountTier?.let { if (!forceRefresh) return it }
 
     val account = getActiveAccount() ?: return CompletableFuture.completedFuture(null)
     val previousAccountTier = activeAccountTier?.getNow(null)
-    val accountTierFuture = CompletableFuture<AccountTier>()
+    val accountTierFuture = CompletableFuture<AccountTier?>()
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt:88]: I do not understand how this can be completed with  `null`.
Where and in what way that completions happen?

Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt:88]: Line 86 is the only place where null can be returned. If the execution passes beyond that line, the result will be non-null, but the type of the future still has to match.

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt:88]: Ah, it happens there:

`val account = getActiveAccount() ?: return CompletableFuture.completedFuture(null)`

So we had wrong return type definition type all along.

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt [hunk 3]
```diff
@@ -43,7 +43,7 @@ class CodyAuthenticationManager(val project: Project) : Disposable {
 
   private val publisher = project.messageBus.syncPublisher(AccountSettingChangeActionNotifier.TOPIC)
 
-  @Volatile private var activeAccountTier: CompletableFuture<AccountTier>? = null
+  @Volatile private var activeAccountTier: CompletableFuture<AccountTier?>? = null
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt:46]: personally, I think it's strange that both the completable and the value are nullable. Why don't we make the completable non-null and the value nullable?

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt (hunk 1 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt:57]: Or until you will get `StackOverflow` :)
It is not safe to do so if function is not `tailrec `

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt:57]: That function does not need to loop into itself, it will be called when the account will change:
```
    ApplicationManager.getApplication()
        .messageBus
        .connect()
        .subscribe(LafManagerListener.TOPIC, LafManagerListener { update() })
```

File: src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt (hunk 3 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt:46]: This is a private variable which isn't visible outside the class. It has to be nullable, because it isn't initialised at construction time.

File: src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt (hunk 1 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/chat/ui/LlmDropdown.kt:57]: In that case, that callback seems to be completely redundant. I'm going to remove it.

**Review by pkukielka — APPROVED** [review]
LGTM
