### PR TITLE
Fix chat/autocomplete for projects with space characters in the file path

### LINKED ISSUE #57532: JetBrains: chat is not working for paths containing space characters
Reported on Discord https://discord.com/channels/969688426372825169/1155409130987716710/1159520321766957116

```java
java.net.URISyntaxException: Illegal character in path at index 24: file://D:/_Projects/_The Happy Dev/the-happy-dev
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3147)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3229)
	at java.base/java.net.URI$Parser.parse(URI.java:3177)
	at java.base/java.net.URI.<init>(URI.java:623)
	at com.sourcegraph.cody.agent.CodyAgent.initialize$lambda$0(CodyAgent.kt:75)
```

Marking as a P0 because this issue prevents chat from working.

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes https://github.com/sourcegraph/sourcegraph/issues/57532

Previously, we manually constructed URIs from file paths, which could lead to a crash during agent initialization when the project path had a space character in it. This PR fixes the problem by using `Path.toUri` instead.

## Test plan

I added a test case to demonstrate that `nio.Path.toUri` doesn't crash on paths with space characters. I tried to use `BasePlatformTestCase` to create a `Project` with a space character in the `basePath` but I couldn't figure out how to create a new `Project`.

### CODE REVIEW

**Review by mkondratek — APPROVED** [review]
lgtm

File: src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt [hunk 1]
```diff
@@ -72,7 +71,7 @@ class CodyAgent(private val project: Project) : Disposable {
                       ClientInfo(
                           name = "JetBrains",
                           version = ConfigUtil.getPluginVersion(),
-                          workspaceRootUri = URI("file://${ConfigUtil.getWorkspaceRoot(project)}"),
```
Comment (Strum355) [inline src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt:75]: Disappointing that the constructor doesnt already handle it 🤔 oh well

**Review by Strum355 — APPROVED** [review]
