### PR TITLE
Reorganised the entity hierarchy of HistoryService.

### LINKED ISSUE #1210: bug: Switching accounts does not switch chats, context repos
### Cody Version

Main b33ee8da1a58527560ea9b05a5976e11421ccfd8

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 12
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

In VSCode, the chats and chat history are related to the signed-in account.

In JetBrains, when I switch accounts, I'm still looking at the same chat. Repos selected from one instance still appear in the context list, but those repos won't exist/may have different IDs/etc. on another instance.

Loom demonstrating: https://www.loom.com/share/02a4773c4ee84782966696e9e36e5928?sid=8bb32b22-2b1b-4fae-b919-4ee1cb2baba2

### Expected behavior

When I switch accounts, I should get chat history and chosen repos related to the signed-in account.

### Additional context

VSCode also makes it much easier to see what account you're signed in to, and whether you're on the pro plan. This is the first thing you see when you click "Account" in VSCode:

Screenshot 2024-03-28 at 15 16 55

### PR DESCRIPTION
**Pull request by odisseus**
Fixes https://github.com/sourcegraph/jetbrains/issues/1210

The chats are now grouped by the account ID, and each account has (optionally) its own enhanced context.

## Test plan
 Added a new test

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt [hunk 1]
```diff
@@ -5,10 +5,8 @@ import com.intellij.util.xmlb.annotations.OptionTag
 
 class HistoryState : BaseState() {
 
-  @get:OptionTag(tag = "chats", nameAttribute = "") var chats: MutableList<ChatState> by list()
+  @get:OptionTag(tag = "accountHistories", nameAttribute = "")
+  var accountHistories: MutableList<AccountHistoryState> by list()
 
   @get:OptionTag(tag = "defaultLlm", nameAttribute = "") var defaultLlm: LLMState? by property()
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt]: Default LLM should also be per account, so we need to move it to `AccountHistoryState`

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt [hunk 2]
```diff
@@ -122,12 +136,16 @@ class HistoryService(private val project: Project) :
...
-    val newChat = ChatState.create(activeAccountId, internalId)
-    state.chats += newChat
-    return newChat
+    val accountHistory = getOrCreateActiveAccountHistory()
+    val found = accountHistory.chats.find { it.internalId == internalId }
+    return found ?: ChatState.create(internalId).also { accountHistory.chats += it }
+  }
+
+  private fun getOrCreateActiveAccountHistory(): AccountHistoryState {
+    val activeAccountId = CodyAuthenticationManager.getInstance(project).getActiveAccount()!!.id
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Please try to never use `!!`.
Either `getActiveAccount` should not return `null` (and then we should change it) or `null` is a valid state (or marker for error) and then we should handle it properly.

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 3]
```diff
@@ -99,32 +99,30 @@ class SettingsMigration : Activity {
   }
 
   private fun migrateLlms(project: Project) {
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: I think that won't work. Past migrations run only once.
If you need to migrate something now you need to add completely new function.
Also this way migrations are linear, changing past migrations is a bit more risky as we can accidentally mess up something in the chain of changes.

So:
1) Please move your migrations to separate methods called after all others
2) Add some test for it

File: src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt (hunk 1 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt (hunk 2 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Fixed

File: src/main/kotlin/com/sourcegraph/cody/history/state/AccountHistoryState.kt [hunk 4]
```diff
@@ -0,0 +1,24 @@
+package com.sourcegraph.cody.history.state
+
+import com.intellij.openapi.components.BaseState
+import com.intellij.util.xmlb.annotations.OptionTag
+
+class AccountHistoryState : BaseState() {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/history/state/AccountHistoryState.kt]: nice 🚀

File: src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt [hunk 5]
```diff
@@ -111,8 +113,10 @@ class EnhancedContextPanel(private val project: Project, private val chatSession
   private fun getContextState(): EnhancedContextState? {
     val historyService = HistoryService.getInstance(project)
 
-    return historyService.getContextReadOnly(chatSession.getInternalId())
-        ?: historyService.getDefaultContextReadOnly()
+    return CodyAuthenticationManager.getInstance(project).getActiveAccount()?.let { _ ->
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt]: why do we need `CodyAuthenticationManager.getInstance(project).getActiveAccount()`?

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt]: oh, this is probably just a null check. if it is so please rewrite it as a regular if-statement to avoid the confusion in the future

File: src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt [hunk 6]
```diff
@@ -40,8 +40,10 @@ class EnhancedContextPanel(private val project: Project, private val chatSession
   private val enhancedContextNode =
       ContextTreeRootNode(CodyBundle.getString("context-panel.tree.node-chat-context")) { isChecked
         ->
-        isEnhancedContextEnabled.set(isChecked)
-        updateContextState { it.isEnabled = isChecked }
+        if (CodyAuthenticationManager.getInstance(project).getActiveAccount() != null) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt]: and can you please put some comment here? the code in the if-statement body seems to be unrelated to the if statement condition

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 7]
```diff
@@ -54,6 +58,29 @@ class SettingsMigration : Activity {
...
+              })
+      newState.defaultLlm = historyState.defaultLlm
+      newState.defaultEnhancedContext = historyState.defaultEnhancedContext
+      if (newState.chats.find { it.internalId == oldState.internalId } == null) {
+        newState.chats.add(oldState)
+      }
+    }
+
+    // TODO is this required in this case?
+    CodyToolWindowContent.executeOnInstanceIfNotDisposed(project) { refreshChatHistoryPanel() }
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: We do not need it here. `CodyToolWindowContent` and `refreshChatHistoryPanel` refer the UI.

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt [hunk 8]
```diff
@@ -9,11 +9,7 @@ import com.intellij.openapi.project.Project
 import com.sourcegraph.cody.agent.protocol.ChatMessage
 import com.sourcegraph.cody.agent.protocol.Speaker
 import com.sourcegraph.cody.config.CodyAuthenticationManager
-import com.sourcegraph.cody.history.state.ChatState
-import com.sourcegraph.cody.history.state.EnhancedContextState
-import com.sourcegraph.cody.history.state.HistoryState
-import com.sourcegraph.cody.history.state.LLMState
-import com.sourcegraph.cody.history.state.MessageState
+import com.sourcegraph.cody.history.state.*
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Personally I do not like wildcard imports (and [here](https://stackoverflow.com/a/147461) is why). 

You can change your IDE settings (and [here](https://stackoverflow.com/a/3348855) is how).

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt [hunk 9]
```diff
@@ -61,45 +57,51 @@ class HistoryService(private val project: Project) :
 
   @Synchronized
   fun updateDefaultContextState(contextState: EnhancedContextState) {
-    state.defaultEnhancedContext = EnhancedContextState()
-    state.defaultEnhancedContext?.copyFrom(contextState)
+    getOrCreateActiveAccountHistory().defaultEnhancedContext = EnhancedContextState()
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: This PR is big enough already but we should consider renaming "History" to "State". It's a bit strange that `updateDefaultContextState` modifies the "history".

File: src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt [hunk 10]
```diff
@@ -5,10 +5,18 @@ import com.intellij.util.xmlb.annotations.OptionTag
 
 class HistoryState : BaseState() {
 
-  @get:OptionTag(tag = "chats", nameAttribute = "") var chats: MutableList<ChatState> by list()
+  @get:OptionTag(tag = "accountHistories", nameAttribute = "")
+  var accountHistories: MutableList<AccountHistoryState> by list()
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt]: Before we introduce more strange naming... Are we sure about `accountHistories`? IMHO the word "history" is redundant and misleading. And has been introduced probably in the context of Chat History panel.

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt [hunk 11]
```diff
@@ -61,45 +57,51 @@ class HistoryService(private val project: Project) :
...
   @Synchronized
-  fun getDefaultLlm(): LLMState? {
-    val defaultLlm = LLMState()
-    defaultLlm.copyFrom(state.defaultLlm ?: return null)
-    return defaultLlm
-  }
+  fun getDefaultLlm(): LLMState? =
+      CodyAuthenticationManager.getInstance(project).getActiveAccount()?.let { account ->
+        findHistory(account.id)?.defaultLlm?.let { llm -> LLMState().also { it.copyFrom(llm) } }
+      }
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: a lot of nesting here 😕 can you make it more readable?

**Review by mkondratek — DISMISSED** [review]

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt [hunk 12]
```diff
@@ -122,12 +124,26 @@ class HistoryService(private val project: Project) :
...
   private fun getOrCreateChat(internalId: String): ChatState {
-    val found = state.chats.find { it.internalId == internalId }
-    if (found != null) return found
-    val activeAccountId = CodyAuthenticationManager.getInstance(project).getActiveAccount()?.id
-    val newChat = ChatState.create(activeAccountId, internalId)
-    state.chats += newChat
-    return newChat
+    val accountHistory = getOrCreateActiveAccountHistory()
+    val found = accountHistory.chats.find { it.internalId == internalId }
+    return found ?: ChatState.create(internalId).also { accountHistory.chats += it }
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Why do we need to use `ChatState.create` in this method?

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 13]
```diff
@@ -54,6 +58,29 @@ class SettingsMigration : Activity {
     }
   }
 
+  private fun migrateHistoryToActiveAccount(project: Project) {
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: Please add test for that method.

File: src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt (hunk 5 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt (hunk 7 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: Removed

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt (hunk 8 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt (hunk 12 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: To be honest, I don't understand why this method wasn't written as a constructor. But given that it already exists, I don't see any problem with using it either.

**P.S.** This seems to be some kind of a pattern, but I don't understand its purpose. I'm going to try refactoring all such functions into constructors.

**P.P.S.** #1325

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt (hunk 11 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt (hunk 9 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Does this structure really contain the whole state associated with an account? If not, the new name wouldn't be a good fit either.

File: src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt (hunk 6 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt (hunk 3 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: true ☝️

Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt (hunk 10 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt]: How about a separate PR to change the existing names? It may be worth doing that _before_ merging this PR.

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt (hunk 13 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt [hunk 14]
```diff
@@ -44,6 +45,9 @@ class SettingsMigration : Activity {
     RunOnceUtil.runOnceForProject(project, "CodyConvertUrlToCodebaseName") {
       migrateUrlsToCodebaseNames(project)
     }
+    RunOnceUtil.runOnceForProject(project, "CodyAccountHistoryMigration") {
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt:48]: Shouldn't that migration be run as last one?

File: src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt [hunk 15]
```diff
@@ -80,6 +80,10 @@ constructor(protected val project: Project, protected val chatSession: ChatSessi
 
   /** Gets the chat session's enhanced context state. */
   protected fun getContextState(): EnhancedContextState? {
+    if (CodyAuthenticationManager.getInstance(project).getActiveAccount() == null) {
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/context/ui/EnhancedContextPanel.kt:83]: Why is that addition needed? Is that a real scenario which happen during your testing?
One could argue that even if there is no active account there is always default context, so that comment is not really true.

File: src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt (hunk 10 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt]: We cannot freely change that names, because they are used to seriallize the history.
When they are out and someone started to use it they is written in the stone.

Although, I think it should be possible to use some mapping, possibly with that `nameAttribute` property from above.

Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt]: I would vote for just name `AccountData`.
`AccountState` sounds more like info about account and in fact, we have class which is called `AccountState` already,

**Review by pkukielka — APPROVED** [review]
LGTM

File: src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt (hunk 10 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/state/HistoryState.kt]: Done

File: src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt (hunk 9 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/history/HistoryService.kt]: Renamed to `getOrCreateActiveAccountEntry`.

File: src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt (hunk 14 above)
Comment (odisseus) [reply src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt:48]: This order seems to be good.
