### PR TITLE
Fix `Generate Unit Test` on Windows

### LINKED ISSUE #1436: JetBrains: Crash occurred while clicking on "Generate Unit Test".
### Cody Version

v5.5.8

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
PythonCore (233.14475.9)
com.soywiz.korge.korge-intellij-plugin (4.0.4)
com.sourcegraph.jetbrains (5.5.8)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with PRO user
3. Open any source code file and right click to open context menu
4. Choose "Cody > Generate Unit Test"

### Observed behavior:
Crash occurred with following stacktrace,
Stacktrace:
```text
java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 46: c:/Users/Jay Gohil/IdeaProjects/jaysVSDemo/\\c:\Users\Jay Gohil\IdeaProjects\jaysVSDemo\BubbleSortTest.java
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$0(CodyAgentClient.java:118)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 46: c:/Users/Jay Gohil/IdeaProjects/jaysVSDemo/\\c:\Users\Jay Gohil\IdeaProjects\jaysVSDemo\BubbleSortTest.java
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:166)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:98)
	at java.base/java.nio.file.Path.of(Path.java:203)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at com.sourcegraph.cody.edit.sessions.FixupSession.createAndSwitchFileIfNeeded(FixupSession.kt:298)
	at com.sourcegraph.cody.edit.sessions.FixupSession.performWorkspaceEdit(FixupSession.kt:268)
	at com.sourcegraph.cody.agent.CodyAgentService$1.invoke$lambda$4(CodyAgentService.kt:60)
	at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$1(CodyAgentClient.java:130)
	at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$0(CodyAgentClient.java:113)
	... 40 more

```

### Expected behavior

Crash should not occur and Cody should generate unit test.

### Additional context

**Video link:**

https://drive.google.com/file/d/1vtE6y_g448Cd7k6YQj2CvTwK5hCgFBY0/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/1436.

Btw it fixes an issue with an error when closing a file that's content is being generated.

## Test plan
1. `Generate Unit Test` on both Windows and macOs

### CODE REVIEW

File: src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt [hunk 1]
```diff
@@ -187,8 +187,10 @@ abstract class FixupSession(
     val future = group.show(range)
     // Make sure the lens is visible.
     ApplicationManager.getApplication().invokeLater {
-      val logicalPosition = LogicalPosition(range.start.line, range.start.character)
-      editor.scrollingModel.scrollTo(logicalPosition, ScrollType.CENTER)
+      if (!editor.isDisposed) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/edit/sessions/FixupSession.kt:206]: unrel fix

---

The error appears when closing the file that contains the content being generated. This fixes it.

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt [hunk 2]
```diff
@@ -47,8 +48,9 @@ private constructor(
       return ProtocolTextDocument(uriFor(file), text, selection)
     }
 
-    fun uriFor(file: VirtualFile): String {
-      return Rfc3986UriEncoder.encode(file.url)
+    private fun uriFor(file: VirtualFile): String {
+      val uriString = FileSystems.getDefault().getPath(file.path).toUri().toString()
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt]: thanks to this we have 
```
file:///c:/Users/mikolaj/blah-blah/blah
```
instead of
```
file://c:/Users/mikolaj/blah-blah/blah
```
(note additional `/` before the disk name)


That fixes the paths in the agent. This one is related directly to the issue with:
```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 46: c:/Users/Jay Gohil/IdeaProjects/jaysVSDemo/\\c:\Users\Jay Gohil\IdeaProjects\jaysVSDemo\BubbleSortTest.java
```
(https://github.com/sourcegraph/jetbrains/issues/1436)

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt [hunk 3]
```diff
@@ -77,11 +77,15 @@ class CodyAgentService(project: Project) : Disposable {
       }
 
       agent.client.onOpenUntitledDocument = Function { params ->
-        val uri = URI.create(params.uri).withScheme("file")
-        if (CodyEditorUtil.createFileIfNeeded(project, uri, params.content) == null)
+        val uri = URI.create(params.uri)
+        if (!uri.path.contains("/")) {
```
Comment (dominiccooney) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt]: Is it worth commenting why? IIUC it is because we produce VirtualFiles, and below `uriFor` ensures they start with `/`?

With that being the case, can you harden this assertion that `uri.path[0]` is `'/'`? Should we log here? Could we throw here instead?

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt [hunk 4]
```diff
@@ -77,11 +77,15 @@ class CodyAgentService(project: Project) : Disposable {
...
+          return@Function false
+        }
+        val fileUri = uri.withScheme("file")
```
Comment (dominiccooney) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt]: I know this is not new, but this seems really dodgy to me. When do we get URIs that aren't `file:`? When would it be OK to take on of those and say randomly, boom, now you're a file path!

**Review by dominiccooney — APPROVED** [review]
Approving to unblock, but can you follow up on the following comment in Slack?

> When does onOpenUntitledDocument get URIs that aren't file:? When would it be OK to take on of those and say randomly, boom, now you're a file path!?

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt (hunk 4 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt]: In fact we always get a files which does not start with `file://` there.
They start with `untitled://` which is VSCode-specific way to say that files does not exist on the disk yet.
I should have added a comment. @mkondratek can you fix my omission and add it now?

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt (hunk 3 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt]: Or even better `startsWith("/")` to avoid crashes in case of empty uri string.

I would also like to see detailed comment why that code looks that way.
I suppose that might be due to a fact that we are not covering all possible file creation requests.
VSCode sometimes creates in-memory files for a temp usage (which have UUID names) and we do not support/care about those.

It's a leftover from my recent changes, perhaps we should improve it on the agent side.

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt (hunk 2 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt]: Cool! Can we removed `Rfc3986UriEncoder` then?

Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt]: it looks like we can indeed!

**Review by pkukielka — APPROVED** [review]
LGTM
