### PR TITLE
Got Cody working with WSL projects on Windows

### LINKED ISSUE #138: WSL PhpStorm [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
## Installation information
PhpStorm 2023.2.3
Build #PS-232.10072.32, built on October 13, 2023
Licensed to XXXXXXXXXXXX
Subscription is active until May 3, 2024.
XXXXXXXXXX
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.watches.in.variables=false
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    com.github.shubham076.darkthemes (3.0.2)
    com.intellij.ideolog (222.1.0.0)
    CMD Support (1.0.5)
    Intellij_GitHub_Dark_Theme (1.1.1)
    net.vektah.codeglance (1.5.4)
    com.intellij.kubernetes (232.10072.33)
    PlantUML integration (7.3.0-IJ2023.2)
    com.alicannklc.laravel.snippets (1.1.1)
    ru.adelf.idea.dotenv (2023.2)
    org.endpointdeps.EndpointDependencies (1.3)
    de.espend.idea.laravel (0.15.4)
    net.seesharpsoft.intellij.plugins.csv (3.2.3-232)
    com.intellij.ml.llm (232.9826)
    com.nekofar.milad.intellij.nuxtjs (2.0.8)
    tv.twelvetone.intellij.plugins.intellivue (1.1.43)
    com.sourcegraph.jetbrains (5.2.7836-nightly)
    com.intellij.jira (4.6.3)
    mobi.hsz.idea.gitignore (4.5.2)

## (optional) Error message or idea.log output
WARN - #com.sourcegraph.cody.agent.CodyAgent - Error: Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

## Steps to reproduce
Using phpstorm for windows and having the repository on WSL. IT seems to not recognize the path to the files. If i set the repository on windows it works as expected. 

## Expected behavior
Normal use

### PR DESCRIPTION
**Pull request by steveyegge**
fixes: CODY-2862

Cody couldn't start up if your repo/project was on a WSL drive/path, e.g., \\wsl.localhost\Ubuntu\home\person\foo -- we didn't handle the new URI syntaxes required here.

I've updated the code to normalize the paths properly. There was also a minor build issue that's fixed in `build.gradle.kts`.

## Test plan

I've tested it manually on Mac, Windows/normal, and Windows/WSL.

I wrote new unit tests for the primary change, which is how we normalize paths.

I will talk to our folks and see if we should add a manual QA pass for WSL projects.

### CODE REVIEW

**Review by steveyegge — COMMENTED** [review]
I just noticed on the plane that this is wrong. It doesn't always normalize the slashes. Will fix on the plane in a bit.

Update August 6th:  I have inspected the code and it does not have the error I thought it had. It's ready to go.

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt [hunk 1]
```diff
@@ -186,12 +194,36 @@ private constructor(
...
-        val driveLetter =
-            it.groups[1]?.value?.lowercase(Locale.getDefault()) ?: return@replace it.value
-        "file:///$driveLetter%3A/"
+      val uriString = FileSystems.getDefault().getPath(file.path).toUri().toString()
+      return normalizeUriOrPath(uriString)
+    }
+
+    @JvmStatic
+    fun normalizeUriOrPath(uriString: String): String {
+      val hasScheme = uriString.startsWith("file://")
```
Comment (pkukielka) [inline src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt:203]: Do we care only about `file` schemes? If so, why?

**Review by pkukielka — COMMENTED** [review]
LGTM except one question I added

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt (hunk 1 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt:203]: I assume we probably do not support other protocols right now anyway, although I think we should support things like `jar://` which are common if one browses files from external libraries (and which still could be useful as open files for chat context).

File: src/test/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocumentTest.kt [hunk 2]
```diff
@@ -223,4 +219,69 @@ class ProtocolTextDocumentTest : BasePlatformTestCase() {
...
+    assertEquals(expected, ProtocolTextDocument.normalizeUriOrPath(input))
+  }
+
+  fun testWindowsPathUpperCase() {
+    val input = "D:/home/person"
+    val expected = "d:/home/person"
+    assertEquals(expected, ProtocolTextDocument.normalizeUriOrPath(input))
+  }
+
+  fun testWslPathWithFileScheme() {
```
Comment (mkondratek) [inline src/test/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocumentTest.kt:264]: 💟

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt (hunk 1 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt:203]: idk if that's directly related to the thing Peter is mentioning here but I could be worth to try to open a file like this:
```
/Users/mkondratek/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2022.1/c91a19824ffcb28872ecd2761c83b250f703ff21/ideaIC-2022.1/lib/app.jar!/com/intellij/openapi/project/Project.class
```

(simply `runIde` with JetBrains project and go to the definition of some library class)

In particular `Explain Code` should work properly in it. 

I'd love to verify it myself but I have no access to my Windows PC till next week.

**Review by mkondratek — COMMENTED** [review]
awesome 🚀 can't wait to have it released and notify the users about the happy news

File: src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt (hunk 1 above)
Comment (steveyegge) [reply src/main/kotlin/com/sourcegraph/cody/agent/protocol/ProtocolTextDocument.kt:203]: Verified that it works; screenshot attached. 
image

**Review by mkondratek — APPROVED** [review]
