### PR TITLE
Make agent restart code much less error-prone

### LINKED ISSUE #439: bug: IntelliJ plugin filled up disk with agent files
### Installation Information

Cody plugin version 5.2.20247 

IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3

### Describe the bug

The plugin seemed stuck in a loop, leading to excessive disk usage. Additionally, it created large temporary copies of the agent file during this process, with many of these logs:

```
2024-01-30 09:34:58,888 [86661021]   INFO - #CodyAgent - extracting Cody agent binary to /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
2024-01-30 09:34:58,920 [86661053]   INFO - #CodyAgent - starting Cody agent /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
```

To mitigate the issue, the user cleared all the files associated with the plugin, restarted the macOS, and then reenabled the plugin. After these actions, the plugin behaves correctly, with only two copies of the agent created.

It seems like the plugin may not clean up after itself properly, as indicated by the excessive number of temporary copies created during the loop.

### Expected behavior

The plugin cleans up temporary files appropriately to prevent excessive disk usage.

### Additional context (logs, images, etc)

Additional context: https://sourcegraph.slack.com/archives/C02842Z6YAK/p1706567669821759

```
2024-01-30 09:34:53,884 [86656017]   INFO - #CodyAgent - extracting Cody agent binary to /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent15487046631569367214
2024-01-30 09:34:53,918 [86656051]   INFO - #CodyAgent - starting Cody agent /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent15487046631569367214
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ getRgPath: Did not find bundled `rg`.
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CommandsController:fileWatcherInit: watchers created
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ AuthProvider:init:lastEndpoint: https://sourcegraph.com/
2024-01-30 09:34:55,103 [86657236]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyIgnore:refresh:workspace: file:///Users/foo/bar/baz/.ijwb/
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatManager:constructor: init no local embeddings
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:constructor: init
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ vscode.commands.executeCommand: not found cody.chat.focus
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-01-30 09:34:57,037 [86659170]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase github.com/foo/bar
2024-01-30 09:34:57,037 [86659170]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-01-30 09:34:57,304 [86659437]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ Cody:publishConfig: configForWebview 
2024-01-30 09:34:57,304 [86659437]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase github.com/foo/bar
2024-01-30 09:34:57,305 [86659438]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ logEvent: CodyJetBrainsPlugin:Auth:failed JetBrains {"opts":{"agent":true}}
2024-01-30 09:34:57,305 [86659438]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.auth/failed: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":2},{"key":"guardrails","value":0}]},"timestamp":"2024-01-29T20:34:57.300Z"}
2024-01-30 09:34:57,305 [86659438]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-01-30 09:34:57,327 [86659460]   INFO - #CodyAgent - Connected to Cody agent cody-agent
2024-01-30 09:34:57,565 [86659698]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ GraphQLTelemetryExporter: evaluated export mode: 5.2.2-5.2.3
2024-01-30 09:34:58,886 [86661019]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:createWebviewPanel: 0
2024-01-30 09:34:58,887 [86661020]   WARN - #CodyAgent - Cody Agent shut down
2024-01-30 09:34:58,888 [86661021]   INFO - #CodyAgent - extracting Cody agent binary to /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
2024-01-30 09:34:58,920 [86661053]   INFO - #CodyAgent - starting Cody agent /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
... repeats
```

```
2024-01-30 08:17:01,833 [81983966]   WARN - #CodyAgent - Unable to start Cody agent
com.sourcegraph.cody.agent.CodyAgentException: failed to create agent binary
Caused by: java.nio.file.FileSystemException: /Users/foo/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/Sourcegraph/agent/agent-macos-arm64 -> /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent7707303340069661988: No space left on device
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:256)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at CodyAgent$Companion.agentBinary(CodyAgent.kt:180)
	at CodyAgent$Companion.startAgentProcess(CodyAgent.kt:86)
	at CodyAgent$Companion.create(CodyAgent.kt:57)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$0(CodyAgentService.kt:37)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### PR DESCRIPTION
**Pull request by pkukielka**
Fixes https://github.com/sourcegraph/jetbrains/issues/439

##
Changes
* Removed agent recovery loop, recovery is now on demand
* Added a bit of defensive code in case of unexpected exceptions
* Added few timeouts in places where we shouldn't wait forever
* Improved robustness of the shutdown
* Added additional safeguard for old agent binary file deletion

## Test plan
I added Thread that was destroying agent process in a fixed time after startup.
I tested durations from 100ms to 10s.
Crashes after 200ms (which simulated complete agent failure) were not spamming the logs with too much info, and were not leaving trash on the disk.
Delay around 4-5s was enough for the chat to recover and give really short answer. It was able to recover infinite amount of times, which means we could survive even repeated crashes or hangs of the agent (if that would ever be the case).

### CODE REVIEW

**Review by beyang — APPROVED** [review]

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt [hunk 1]
```diff
@@ -233,6 +234,7 @@ private constructor(
       }
       val binaryTarget = Files.createTempFile("cody-agent", binarySuffix())
       return try {
+        binaryTarget?.toFile()?.deleteOnExit()
```
Comment (olafurpg) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt:238]: We are already doing this here, but not a problem to do it again here https://sourcegraph.com/github.com/sourcegraph/jetbrains@6f75c53354eddb882e15e985ebabc711c5f2e3d2/-/blob/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt?L246

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt [hunk 2]
```diff
@@ -16,7 +17,8 @@ import java.util.function.Consumer
 class CodyAgentService(project: Project) : Disposable {
 
   private val logger = Logger.getInstance(CodyAgent::class.java)
-  private var codyAgent: CompletableFuture<CodyAgent> = CompletableFuture()
+  private var codyAgent: AtomicReference<CompletableFuture<CodyAgent>> =
```
Comment (olafurpg) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt]: It doesn't feel like `AtomicReference` is doing much work here when we're not using operators like compareAndSet. I suppose it's working similar to a `volatile` variable.

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻 This is a critical improvement over the previous while loop.

I think there's still room for improvement to make things more robust, and I'd love to have a call early next week to review together the logic for starting agent processes. I feel like we should never return the original `agent: CompletableFuture<>` instance. Instead, we should maybe do something like

```kotlin
val requestQueue: Queue<CompletableFuture<Agent>>

fun getInitializedAgent(project): CompletableFuture<Agent> {
  val result = CompletableFuture()
  requestsQueue.push(result)
  return result
}
```

Then we have a worker that polls the request queue (ideally non-blocking) and resolves the futures with 100% valid agent instances. Having a queue allows us to complete document synchronization before we respond to autocomplete/chat/command requests even if those requests were submitted at the time of a "live" agent.

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt (hunk 1 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt:238]: Ah, I missed that, no sense to do it twice then, I will never that change.

Comment (olafurpg) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt:238]: I think it's a bit more robust to call this API immediately after creating the file as you have done in this PR

File: src/main/java/com/sourcegraph/cody/CodyFocusChangeListener.java [hunk 3]
```diff
@@ -45,17 +45,17 @@ public void focusGained(@NotNull Editor editor) {
...
-            Thread.sleep(100);
-          } catch (InterruptedException ignored) {
-          }
-          agent.getServer().textDocumentDidFocus(TextDocument.fromPath(file.getPath()));
-        });
+    CodyAgentService.withAgent(project)
+        .thenAccept(
+            agent -> {
+              try {
+                // TODO: This is bad but needed to avoid race with file context of commands executed
```
Comment (mkondratek) [inline src/main/java/com/sourcegraph/cody/CodyFocusChangeListener.java:52]: oh, this TODO was here already. ok then. I wonder if we have any idea how to fix it some day 🤔

File: src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java [hunk 4]
```diff
@@ -65,9 +65,13 @@ private static JsonObject addGlobalEventParameters(
   // This could be exposed later (as public), but currently, we don't use it externally.
   private static CompletableFuture<Boolean> logEvent(
       @NotNull Project project, @NotNull Event event) {
-    return CodyAgentService.getAgent(project)
-        .thenApply(agent -> agent.getServer().logEvent(event))
-        .thenApply((ignored) -> true)
-        .exceptionally((ignored) -> false);
+    return CodyAgentService.withAgent(project)
+        .thenCompose(
+            agent ->
```
Comment (mkondratek) [inline src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java:70]: nit: you can just use `it` instead of the named argument

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt [hunk 5]
```diff
@@ -32,10 +32,11 @@ private constructor(
...
 ) {
 
-  fun shutdown(): CompletableFuture<Void> {
-    return server.shutdown().thenAccept {
+  fun shutdown(): CompletableFuture<Unit> {
+    return server.shutdown().completeOnTimeout(null, 15, TimeUnit.SECONDS).handle { _, throwable ->
+      if (throwable != null) logger.warn("Graceful shutdown of Cody agent server failed", throwable)
       server.exit()
-      logger.warn("Cody Agent shut down")
+      logger.info("Cody Agent shut down")
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt]: Or even `"Cody Agent shut down gracefully"` to reflect that things succeeded

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt [hunk 6]
```diff
@@ -244,7 +246,6 @@ private constructor(
         Files.copy(binarySource, binaryTarget, StandardCopyOption.REPLACE_EXISTING)
         val binary = binaryTarget.toFile()
         if (binary.setExecutable(true)) {
-          binary.deleteOnExit()
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt:247]: so did we delete the file here? how did the problems appear then?

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt [hunk 7]
```diff
@@ -177,7 +177,7 @@ private constructor(
   }
 
   override fun sendWebviewMessage(message: WebviewMessage) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:208]: note: this is enable / disable remote in particular - I guess we are ok with it

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt [hunk 8]
```diff
@@ -108,27 +115,35 @@ class CodyAgentService(project: Project) : Disposable {
...
-    @JvmStatic
-    fun getAgent(project: Project): CompletableFuture<CodyAgent> {
-      return getInstance(project).getInitializedAgent(project)
+      return result
     }
 
     @JvmStatic
     fun isConnected(project: Project): Boolean {
-      return getAgent(project).getNow(null)?.isConnected() == true
+      return getInstance(project).getInitializedAgent(project, false).getNow(null)?.isConnected() ==
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt]: nit: pls name `false` param

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt [hunk 9]
```diff
@@ -108,27 +115,35 @@ class CodyAgentService(project: Project) : Disposable {
...
+      return result
     }
 
     @JvmStatic
-    fun withAgentOnUIThread(project: Project, block: Consumer<CodyAgent>) {
-      getInstance(project).getInitializedAgent(project).thenAccept { agent ->
-        ApplicationManager.getApplication().invokeLater { block.accept(agent) }
+    fun withAgentRestartIfNeeded(project: Project): CompletableFuture<CodyAgent> {
+      val result = CompletableFuture<CodyAgent>()
+      if (CodyApplicationSettings.instance.isCodyEnabled) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt:133]: What about the "else" case? 🤔 is it ok to NOT complete it? my thinking is it will make all the calls to the result waiting for a future that will never be completed.

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt [hunk 10]
```diff
@@ -108,27 +115,35 @@ class CodyAgentService(project: Project) : Disposable {
     }
 
     @JvmStatic
-    fun applyAgentOnBackgroundThread(project: Project, block: Consumer<CodyAgent>) {
-      getInstance(project).getInitializedAgent(project).thenAccept { agent ->
-        ApplicationManager.getApplication().executeOnPooledThread { block.accept(agent) }
+    fun withAgent(project: Project): CompletableFuture<CodyAgent> {
+      val result = CompletableFuture<CodyAgent>()
+      if (CodyApplicationSettings.instance.isCodyEnabled) {
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt:120]: I have the same question here as above ☝️

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt [hunk 11]
```diff
@@ -16,7 +19,7 @@ import java.util.function.Consumer
 class CodyAgentService(project: Project) : Disposable {
 
   private val logger = Logger.getInstance(CodyAgent::class.java)
-  private var codyAgent: CompletableFuture<CodyAgent> = CompletableFuture()
+  @Volatile private var codyAgent: CompletableFuture<CodyAgent> = CompletableFuture()
```
Comment (mkondratek) [inline src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt:22]: > Marks the JVM backing field of the annotated property as `volatile`, meaning that writes to this field are immediately made visible to other threads.

Will the result be the same as when we use `synchronized`?

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt (hunk 6 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt:247]: This only happens on jvm exit, not on the agent crash.
And then I guess maybe whole PR was crashing :)

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt (hunk 11 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt:22]: Kind of, but I do not need to do it in 5 places.

File: src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt (hunk 9 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentService.kt:133]: Hm, you are right, as previously it was a bit different (callback was never called).
Still, there ideally should be no calls to agent when cody is disabled, so this is mostly additional safeguard. 
Let me think for a moment if we can do anything more useful there.

File: src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java (hunk 4 above)
Comment (pkukielka) [reply src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java:70]: It is java :)

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt (hunk 7 above)
Comment (pkukielka) [reply src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:208]: I do not understand that comment :)

File: src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java (hunk 4 above)
Comment (mkondratek) [reply src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java:70]: ah...

File: src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt (hunk 7 above)
Comment (mkondratek) [reply src/main/kotlin/com/sourcegraph/cody/chat/AgentChatSession.kt:208]: I just pointed out where we call it and hence, where `withAgentRestartIfNeeded` is possible - all good

**Review by mkondratek — APPROVED** [review]
